#!/usr/bin/env python3
"""Generate deterministic Copilot and Claude wrappers from one canonical fleet.

The generator is intentionally stdlib-only. Markdown bodies and the shared
skill are sources; runtime-specific frontmatter, manifests, hooks, and the
compatibility report are projections and must never be hand-edited.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
import sys
import tempfile
from pathlib import Path, PurePosixPath


class ManifestError(ValueError):
    """The canonical spike manifest is invalid."""


NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
VERSION_RE = re.compile(r"^\d+\.\d+\.\d+$")
KNOWN_CAPABILITIES = frozenset({"read", "search", "execute", "edit", "web"})
TOP_KEYS = frozenset({
    "schema_version", "plugin", "models", "commands", "skills", "agents",
})
PLUGIN_KEYS = frozenset({"name", "version", "description", "author"})
AUTHOR_KEYS = frozenset({"name"})
MODEL_KEYS = frozenset({"copilot", "claude"})
BUNDLE_KINDS = ("references", "assets", "scripts")
SKILL_KEYS = frozenset({"name", "directory", *BUNDLE_KINDS})
AGENT_KEYS = frozenset({
    "name", "description", "body", "capabilities", "skills", "delegates_to", "handoffs",
})
HANDOFF_KEYS = frozenset({"agent", "label", "prompt", "send"})
GENERATED_BANNER = "# GENERATED by scripts/generate.py"
OWNED_WRAPPER_DIRECTORIES = (
    Path("generated/copilot/agents"),
    Path("generated/claude/agents"),
)


def _unknown_keys(value: dict, known: frozenset[str], where: str) -> None:
    unknown = sorted(set(value) - known)
    if unknown:
        raise ManifestError(f"{where}: unknown {where} key(s): {', '.join(unknown)}")


def _require_string(value: object, where: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ManifestError(f"{where}: expected a non-empty string")
    if value != value.strip() or not value.isprintable():
        raise ManifestError(
            f"{where}: expected trimmed, single-line printable text"
        )
    return value


def _require_string_list(value: object, where: str) -> list[str]:
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise ManifestError(f"{where}: expected a list of strings")
    if len(value) != len(set(value)):
        raise ManifestError(f"{where}: duplicate values are not allowed")
    return value


def _reject_duplicate_json_keys(pairs: list[tuple[str, object]]) -> dict:
    """Build one JSON object while rejecting ambiguous duplicate members."""
    result: dict = {}
    for key, value in pairs:
        if key in result:
            raise ManifestError(f"canonical manifest has duplicate JSON key: {key}")
        result[key] = value
    return result


def _validate_models(manifest: dict) -> dict[str, list[str] | str | None]:
    if "models" not in manifest:
        return {"copilot": [], "claude": None}
    models = manifest["models"]
    if not isinstance(models, dict):
        raise ManifestError("models: expected an object")
    _unknown_keys(models, MODEL_KEYS, "models")
    missing = sorted(MODEL_KEYS - set(models))
    if missing:
        raise ManifestError(f"models: missing required key(s): {', '.join(missing)}")

    copilot = _require_string_list(models["copilot"], "models.copilot")
    if any(
        not model.strip() or model != model.strip() or not model.isprintable()
        for model in copilot
    ):
        raise ManifestError(
            "models.copilot: model names must be trimmed, non-empty, "
            "single-line printable strings"
        )
    claude = models["claude"]
    if claude is not None and (
        not isinstance(claude, str)
        or not claude.strip()
        or claude != claude.strip()
        or not claude.isprintable()
    ):
        raise ManifestError(
            "models.claude: expected a trimmed, non-empty, single-line "
            "printable string or null"
        )
    return {"copilot": copilot, "claude": claude}


def _normalize_bundle_paths(value: object, kind: str, where: str) -> set[str]:
    paths = _require_string_list(value, f"{where}.{kind}")
    normalized: set[str] = set()
    singular = kind[:-1]
    for raw in paths:
        path = PurePosixPath(raw)
        canonical = path.as_posix()
        if (
            not raw.strip()
            or "\\" in raw
            or path.is_absolute()
            or ".." in path.parts
            or len(path.parts) < 2
            or path.parts[0] != kind
            or canonical != raw
        ):
            raise ManifestError(f"{where}: invalid {singular} path '{raw}'")
        if canonical in normalized:
            raise ManifestError(
                f"{where}.{kind}: duplicate normalized path '{canonical}'"
            )
        normalized.add(canonical)
    return normalized


def _is_link_or_junction(path: Path) -> bool:
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        return False
    except OSError as exc:
        raise ManifestError(f"cannot inspect path for links or junctions: {path}") from exc
    if stat.S_ISLNK(metadata.st_mode):
        return True
    attributes = getattr(metadata, "st_file_attributes", 0)
    reparse_point = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    return bool(attributes & reparse_point)


def _require_plain_contained_path(path: Path, root: Path, where: str) -> None:
    try:
        relative = path.relative_to(root)
    except ValueError as exc:
        raise ManifestError(f"{where}: path escapes its owned root: {path}") from exc
    current = root
    for part in relative.parts:
        current = current / part
        if _is_link_or_junction(current):
            raise ManifestError(f"{where}: link or junction is not allowed: {current}")
    try:
        resolved = path.resolve(strict=True)
        resolved.relative_to(root.resolve(strict=True))
    except (OSError, ValueError) as exc:
        raise ManifestError(f"{where}: path escapes its owned root: {path}") from exc


def _canonical_root(root: Path) -> Path:
    canonical = root / "canonical"
    if _is_link_or_junction(canonical):
        raise ManifestError(
            f"canonical root cannot be a link or junction: {canonical}"
        )
    if not canonical.is_dir():
        raise ManifestError(f"canonical root must be a directory: {canonical}")
    _require_plain_contained_path(canonical, root, "canonical root")
    return canonical


def _walk_tree_without_following_links(root: Path):
    """Yield descendants while pruning links/junctions before descent."""
    for current, directory_names, file_names in os.walk(
        root, topdown=True, followlinks=False,
    ):
        current_path = Path(current)
        safe_directory_names: list[str] = []
        for name in directory_names:
            candidate = current_path / name
            yield candidate
            if not _is_link_or_junction(candidate):
                safe_directory_names.append(name)
        directory_names[:] = safe_directory_names
        for name in file_names:
            yield current_path / name


def _validate_default_discovery_paths(root: Path) -> None:
    default_agents = root / "agents"
    if _is_link_or_junction(default_agents):
        raise ManifestError(f"default agent directory cannot be a link or junction: {default_agents}")
    if default_agents.exists():
        if not default_agents.is_dir():
            raise ManifestError(f"default agent path must be a directory: {default_agents}")
        for candidate in _walk_tree_without_following_links(default_agents):
            if _is_link_or_junction(candidate):
                raise ManifestError(
                    f"default agent path contains a link or junction: {candidate}"
                )
            if candidate.is_file():
                relative = candidate.relative_to(root).as_posix()
                raise ManifestError(
                    f"unexpected default agent source bypasses canonical inventory: {relative}"
                )
    root_skill = root / "SKILL.md"
    if root_skill.exists() or _is_link_or_junction(root_skill):
        raise ManifestError(
            "unexpected root SKILL.md bypasses canonical skill inventory"
        )


def _source_path(root: Path, relative: str) -> Path:
    canonical = _canonical_root(root)
    candidate_path = canonical / relative
    _require_plain_contained_path(candidate_path, canonical, "body source")
    if not candidate_path.is_file():
        raise ManifestError(f"body path does not exist: {relative}")
    return candidate_path


def compare_skill_inventory(
    expected: dict[str, dict[str, set[str]]],
    actual_directories: set[str],
    actual_inventory: dict[str, dict[str, set[str]]],
) -> list[str]:
    """Compare canonical bundled-skill inventory without touching the filesystem."""
    issues: list[str] = []
    expected_directories = set(expected)
    for directory in sorted(expected_directories - actual_directories):
        issues.append(f"missing runtime-visible skill directory: {directory}")
    for directory in sorted(actual_directories - expected_directories):
        issues.append(f"unexpected runtime-visible skill directory: {directory}")
    for directory in sorted(expected_directories & actual_directories):
        for kind in BUNDLE_KINDS:
            singular = kind[:-1]
            wanted = expected[directory].get(kind, set())
            found = actual_inventory.get(directory, {}).get(kind, set())
            for relative in sorted(wanted - found):
                issues.append(
                    f"skill '{directory}' missing inventoried {singular}: {relative}"
                )
            for relative in sorted(found - wanted):
                issues.append(
                    f"skill '{directory}' has unexpected runtime-visible "
                    f"{singular}: {relative}"
                )
    return issues


def compare_agent_body_inventory(expected: set[str], actual: set[str]) -> list[str]:
    """Compare canonical agent-body paths without touching the filesystem."""
    issues: list[str] = []
    for body in sorted(expected - actual):
        issues.append(f"missing canonical agent body: {body}")
    for body in sorted(actual - expected):
        issues.append(f"unexpected canonical agent body: {body}")
    return issues


def _skill_frontmatter_name(text: str, path: Path) -> str:
    if not text.startswith("---"):
        raise ManifestError(f"skill has no YAML frontmatter: {path}")
    parts = text.split("---", 2)
    if len(parts) != 3:
        raise ManifestError(f"skill has unterminated YAML frontmatter: {path}")
    matches = re.findall(r"^name\s*:\s*([^\s#]+)\s*$", parts[1], re.MULTILINE)
    if len(matches) != 1:
        raise ManifestError(f"skill must declare exactly one frontmatter name: {path}")
    return matches[0]


def _linked_references(text: str) -> set[str]:
    links: set[str] = set()
    for match in re.finditer(r"\[[^\]]*\]\(([^)]+)\)", text):
        target = match.group(1).strip().split("#", 1)[0]
        if target.startswith("./"):
            target = target[2:]
        if target.startswith("references/") or target.startswith("references\\"):
            path = PurePosixPath(target)
            if (
                "\\" in target
                or path.is_absolute()
                or ".." in path.parts
                or len(path.parts) < 2
                or path.parts[0] != "references"
                or path.as_posix() != target
            ):
                raise ManifestError(f"invalid reference link path '{target}'")
            links.add(path.as_posix())
    return links


def compare_reference_links(
    skill_name: str, expected: set[str], linked: set[str],
) -> list[str]:
    """Compare canonical reference inventory with links from a SKILL body."""
    issues: list[str] = []
    missing = sorted(expected - linked)
    extra = sorted(linked - expected)
    if missing:
        issues.append(
            f"skill '{skill_name}' has unlinked inventoried references: {', '.join(missing)}"
        )
    if extra:
        issues.append(
            f"skill '{skill_name}' links un-inventoried references: {', '.join(extra)}"
        )
    return issues


def _inventory_skill_tree(skill_dir: Path, skill_name: str) -> dict[str, set[str]]:
    allowed_root_entries = {"SKILL.md", *BUNDLE_KINDS}
    for entry in skill_dir.iterdir():
        _require_plain_contained_path(entry, skill_dir, f"skill '{skill_name}'")
        if entry.name not in allowed_root_entries:
            relative = entry.relative_to(skill_dir).as_posix()
            raise ManifestError(
                f"skill '{skill_name}' has unexpected skill path: {relative}"
            )
        if entry.name == "SKILL.md" and not entry.is_file():
            raise ManifestError(f"skill '{skill_name}' SKILL.md is not a file")
        if entry.name in BUNDLE_KINDS and not entry.is_dir():
            raise ManifestError(
                f"skill '{skill_name}' bundle root is not a directory: {entry.name}"
            )

    inventory: dict[str, set[str]] = {}
    for kind in BUNDLE_KINDS:
        bundle_root = skill_dir / kind
        if not bundle_root.exists():
            inventory[kind] = set()
            continue
        _require_plain_contained_path(
            bundle_root, skill_dir, f"skill '{skill_name}' {kind} root"
        )
        files: set[str] = set()
        for candidate in _walk_tree_without_following_links(bundle_root):
            _require_plain_contained_path(
                candidate, skill_dir, f"skill '{skill_name}' bundled path"
            )
            if candidate.is_file():
                files.add(candidate.relative_to(skill_dir).as_posix())
            elif not candidate.is_dir():
                raise ManifestError(
                    f"skill '{skill_name}' has unsupported bundled path: {candidate}"
                )
        inventory[kind] = files
    return inventory


def _validate_skills(manifest: dict, root: Path) -> set[str]:
    skills = manifest.get("skills")
    if not isinstance(skills, list):
        raise ManifestError("skills: expected a list")
    expected_inventory: dict[str, dict[str, set[str]]] = {}
    skill_names: set[str] = set()
    for index, skill in enumerate(skills):
        where = f"skill[{index}]"
        if not isinstance(skill, dict):
            raise ManifestError(f"{where}: expected an object")
        _unknown_keys(skill, SKILL_KEYS, where)
        missing_inventory_keys = sorted(set(BUNDLE_KINDS) - set(skill))
        if missing_inventory_keys:
            raise ManifestError(
                f"{where}: missing required key(s): {', '.join(missing_inventory_keys)}"
            )
        name = _require_string(skill.get("name"), f"{where}.name")
        if not NAME_RE.fullmatch(name):
            raise ManifestError(f"{where}.name must be kebab-case")
        if name in skill_names:
            raise ManifestError(f"duplicate canonical skill name: {name}")
        skill_names.add(name)
        directory_value = _require_string(skill.get("directory"), f"{where}.directory")
        directory = PurePosixPath(directory_value)
        if (
            "\\" in directory_value
            or directory.is_absolute()
            or ".." in directory.parts
            or len(directory.parts) != 2
            or directory.parts[0] != "skills"
            or directory.as_posix() != directory_value
        ):
            raise ManifestError(f"{where}.directory must be skills/<name>")
        if directory.name != name:
            raise ManifestError(
                f"{where}: skill name '{name}' does not match directory '{directory.name}'"
            )
        skill_dir = root / Path(directory.as_posix())
        skills_root = root / "skills"
        try:
            skill_dir.resolve().relative_to(skills_root.resolve())
        except ValueError as exc:
            raise ManifestError(f"{where}.directory escapes skills/: {directory_value}") from exc
        skill_file = skill_dir / "SKILL.md"
        if not skill_file.is_file():
            raise ManifestError(f"{where}: missing SKILL.md at {skill_file}")
        _require_plain_contained_path(skill_dir, skills_root, where)
        _require_plain_contained_path(skill_file, skill_dir, where)
        skill_text = skill_file.read_text(encoding="utf-8")
        frontmatter_name = _skill_frontmatter_name(skill_text, skill_file)
        if frontmatter_name != name:
            raise ManifestError(
                f"{where}: frontmatter name '{frontmatter_name}' does not match '{name}'"
            )
        bundled = {
            kind: _normalize_bundle_paths(skill[kind], kind, where)
            for kind in BUNDLE_KINDS
        }
        linked = _linked_references(skill_text)
        link_problems = compare_reference_links(name, bundled["references"], linked)
        if link_problems:
            raise ManifestError(f"{where}: reference link parity failed ({'; '.join(link_problems)})")
        expected_inventory[name] = bundled

    skills_root = root / "skills"
    if _is_link_or_junction(skills_root):
        raise ManifestError(f"skills root cannot be a link or junction: {skills_root}")
    actual_directories: set[str] = set()
    if skills_root.is_dir():
        for child in skills_root.iterdir():
            if _is_link_or_junction(child):
                raise ManifestError(f"skills root contains a link or junction: {child}")
            if child.is_dir():
                actual_directories.add(child.name)
            elif child.name != ".gitkeep":
                raise ManifestError(
                    "unexpected runtime-visible file at skills root: "
                    f"{child.relative_to(root).as_posix()}"
                )
    actual_inventory: dict[str, dict[str, set[str]]] = {}
    for directory in actual_directories:
        skill_root = skills_root / directory
        if directory in expected_inventory:
            actual_inventory[directory] = _inventory_skill_tree(skill_root, directory)
    inventory_problems = compare_skill_inventory(
        expected_inventory, actual_directories, actual_inventory,
    )
    if inventory_problems:
        raise ManifestError("; ".join(inventory_problems))
    return skill_names


def _validate_commands(manifest: dict, root: Path) -> list[str]:
    declared = _require_string_list(manifest.get("commands"), "commands")
    expected: set[str] = set()
    for index, raw in enumerate(declared):
        path = PurePosixPath(raw)
        if (
            not raw.strip()
            or "\\" in raw
            or path.is_absolute()
            or ".." in path.parts
            or len(path.parts) != 2
            or path.parts[0] != "commands"
            or path.suffix != ".md"
            or not NAME_RE.fullmatch(path.stem)
            or path.as_posix() != raw
        ):
            raise ManifestError(
                f"commands[{index}]: expected commands/<kebab-name>.md"
            )
        expected.add(raw)

    commands_root = root / "commands"
    if _is_link_or_junction(commands_root):
        raise ManifestError(
            f"commands root cannot be a link or junction: {commands_root}"
        )
    if commands_root.exists() and not commands_root.is_dir():
        raise ManifestError(f"commands root must be a directory: {commands_root}")

    actual: set[str] = set()
    if commands_root.is_dir():
        _require_plain_contained_path(commands_root, root, "commands root")
        for candidate in _walk_tree_without_following_links(commands_root):
            if _is_link_or_junction(candidate):
                raise ManifestError(
                    f"canonical command cannot be a link or junction: {candidate}"
                )
            if candidate.is_dir():
                raise ManifestError(
                    "unexpected canonical command directory: "
                    f"{candidate.relative_to(root).as_posix()}"
                )
            if candidate.is_file() and candidate.name != ".gitkeep":
                _require_plain_contained_path(
                    candidate, commands_root, "canonical command"
                )
                actual.add(candidate.relative_to(root).as_posix())

    problems = [
        *(f"missing canonical command: {relative}" for relative in sorted(expected - actual)),
        *(
            f"unexpected canonical command: {relative}"
            for relative in sorted(actual - expected)
        ),
    ]
    if problems:
        raise ManifestError("; ".join(problems))

    for relative in declared:
        source = root / relative
        source_bytes = source.read_bytes()
        if not source_bytes.endswith(b"\n"):
            raise ManifestError(f"canonical command must end with a line feed: {relative}")
        try:
            content = source_bytes.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise ManifestError(f"canonical command must be UTF-8: {relative}") from exc
        if not content.strip():
            raise ManifestError(f"canonical command must not be empty: {relative}")
    return declared


def load_manifest(root: Path) -> dict:
    canonical = _canonical_root(root)
    path = canonical / "fleet.json"
    if _is_link_or_junction(path):
        raise ManifestError(
            f"canonical manifest cannot be a link or junction: {path}"
        )
    if not path.is_file():
        raise ManifestError(f"canonical manifest missing: {path}")
    _require_plain_contained_path(path, canonical, "canonical manifest")
    try:
        value = json.loads(
            path.read_text(encoding="utf-8"),
            object_pairs_hook=_reject_duplicate_json_keys,
        )
    except json.JSONDecodeError as exc:
        raise ManifestError(f"canonical manifest is invalid JSON: {exc}") from exc
    if not isinstance(value, dict):
        raise ManifestError("canonical manifest must be a JSON object")
    validate_manifest(value, root)
    return value


def validate_manifest(manifest: dict, root: Path) -> None:
    if not isinstance(manifest, dict):
        raise ManifestError("canonical manifest must be a JSON object")
    _unknown_keys(manifest, TOP_KEYS, "top-level")
    if manifest.get("schema_version") != 1:
        raise ManifestError("schema_version must be 1")
    canonical_root = _canonical_root(root)

    plugin = manifest.get("plugin")
    if not isinstance(plugin, dict):
        raise ManifestError("plugin: expected an object")
    _unknown_keys(plugin, PLUGIN_KEYS, "plugin")
    plugin_name = _require_string(plugin.get("name"), "plugin.name")
    if not NAME_RE.fullmatch(plugin_name):
        raise ManifestError("plugin.name must be kebab-case")
    version = _require_string(plugin.get("version"), "plugin.version")
    if not VERSION_RE.fullmatch(version):
        raise ManifestError("plugin.version must be MAJOR.MINOR.PATCH")
    _require_string(plugin.get("description"), "plugin.description")
    author = plugin.get("author")
    if not isinstance(author, dict):
        raise ManifestError("plugin.author: expected an object")
    _unknown_keys(author, AUTHOR_KEYS, "author")
    _require_string(author.get("name"), "plugin.author.name")

    _validate_default_discovery_paths(root)
    _validate_models(manifest)
    _validate_commands(manifest, root)
    skill_names = _validate_skills(manifest, root)

    agents = manifest.get("agents")
    if not isinstance(agents, list):
        raise ManifestError("agents: expected a list")

    names: list[str] = []
    expected_bodies: set[str] = set()
    for index, agent in enumerate(agents):
        where = f"agent[{index}]"
        if not isinstance(agent, dict):
            raise ManifestError(f"{where}: expected an object")
        unknown = sorted(set(agent) - AGENT_KEYS)
        if unknown:
            raise ManifestError(f"unknown agent key(s) in {where}: {', '.join(unknown)}")
        name = _require_string(agent.get("name"), f"{where}.name")
        if not NAME_RE.fullmatch(name):
            raise ManifestError(f"{where}.name must be kebab-case")
        names.append(name)
        _require_string(agent.get("description"), f"{where}.description")
        body = _require_string(agent.get("body"), f"{where}.body")
        body_path = PurePosixPath(body)
        normalized_body = body_path.as_posix()
        required_body = f"agents/{name}.md"
        if (
            "\\" in body
            or body_path.is_absolute()
            or ".." in body_path.parts
            or normalized_body != body
        ):
            raise ManifestError(f"{where}.body must be canonical POSIX relative path")
        if normalized_body != required_body:
            raise ManifestError(
                f"{where}.body must be {required_body} for explicit agent name '{name}'"
            )
        source = _source_path(root, body)
        source_bytes = source.read_bytes()
        if not source_bytes.endswith(b"\n"):
            raise ManifestError(f"{where}.body must end with a line feed")
        try:
            source_bytes.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise ManifestError(f"{where}.body must be UTF-8") from exc
        expected_bodies.add(normalized_body)
        capabilities = _require_string_list(agent.get("capabilities"), f"{where}.capabilities")
        for capability in capabilities:
            if capability not in KNOWN_CAPABILITIES:
                raise ManifestError(f"{where}: unknown capability '{capability}'")
        skill_dependencies = _require_string_list(agent.get("skills"), f"{where}.skills")
        unknown_dependencies = sorted(set(skill_dependencies) - skill_names)
        if unknown_dependencies:
            raise ManifestError(
                f"{where}: unknown skill dependency: {', '.join(unknown_dependencies)}"
            )
        delegates = _require_string_list(agent.get("delegates_to"), f"{where}.delegates_to")
        if not capabilities and not skill_dependencies and not delegates:
            raise ManifestError(
                f"{where}: expected at least one capability, skill dependency, or delegate"
            )
        handoffs = agent.get("handoffs")
        if not isinstance(handoffs, list):
            raise ManifestError(f"{where}.handoffs: expected a list")
        for handoff_index, handoff in enumerate(handoffs):
            hwhere = f"{where}.handoffs[{handoff_index}]"
            if not isinstance(handoff, dict):
                raise ManifestError(f"{hwhere}: expected an object")
            unknown_handoff = sorted(set(handoff) - HANDOFF_KEYS)
            if unknown_handoff:
                raise ManifestError(f"{hwhere}: unknown key(s): {', '.join(unknown_handoff)}")
            _require_string(handoff.get("agent"), f"{hwhere}.agent")
            _require_string(handoff.get("label"), f"{hwhere}.label")
            _require_string(handoff.get("prompt"), f"{hwhere}.prompt")
            if not isinstance(handoff.get("send"), bool):
                raise ManifestError(f"{hwhere}.send: expected a boolean")

    if len(names) != len(set(names)):
        raise ManifestError("agent names must be unique")
    agents_root = canonical_root / "agents"
    if _is_link_or_junction(agents_root):
        raise ManifestError(f"canonical agents root cannot be a link or junction: {agents_root}")
    if agents_root.exists():
        _require_plain_contained_path(
            agents_root, canonical_root, "canonical agents root"
        )
    actual_bodies: set[str] = set()
    if agents_root.is_dir():
        for path in _walk_tree_without_following_links(agents_root):
            if _is_link_or_junction(path):
                raise ManifestError(f"canonical agent path cannot be a link or junction: {path}")
            if path.is_dir():
                raise ManifestError(
                    "unexpected canonical agent directory: "
                    f"{path.relative_to(root / 'canonical').as_posix()}"
                )
            if path.is_file() and path.name != ".gitkeep":
                actual_bodies.add(path.relative_to(root / "canonical").as_posix())
    body_inventory_problems = compare_agent_body_inventory(expected_bodies, actual_bodies)
    if body_inventory_problems:
        raise ManifestError("; ".join(body_inventory_problems))
    known_names = set(names)
    for agent in agents:
        name = agent["name"]
        for target in agent["delegates_to"]:
            if target not in known_names:
                raise ManifestError(f"agent '{name}' delegates to unknown agent '{target}'")
            if target == name:
                raise ManifestError(f"agent '{name}' cannot delegate to itself")
        for handoff in agent["handoffs"]:
            if handoff["agent"] not in known_names:
                raise ManifestError(
                    f"agent '{name}' hands off to unknown agent '{handoff['agent']}'"
                )


def _json_bytes(value: object) -> bytes:
    return (json.dumps(value, indent=2, ensure_ascii=False) + "\n").encode("utf-8")


def _flow_list(values: list[str]) -> str:
    return "[" + ", ".join("'" + value.replace("'", "''") + "'" for value in values) + "]"


def _body_and_hash(root: Path, agent: dict) -> tuple[str, str]:
    body_bytes = _source_path(root, agent["body"]).read_bytes()
    try:
        body = body_bytes.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ManifestError(f"agent body must be UTF-8: {agent['body']}") from exc
    if not body_bytes.endswith(b"\n"):
        raise ManifestError(f"agent body must end with a line feed: {agent['body']}")
    return body, hashlib.sha256(body_bytes).hexdigest()


def _copilot_agent(
    root: Path, agent: dict, models: dict[str, list[str] | str | None],
) -> bytes:
    capabilities = set(agent["capabilities"])
    tools: list[str] = []
    if "read" in capabilities:
        tools.append("read")
    if "search" in capabilities:
        tools.append("search")
    if "execute" in capabilities:
        tools.append("execute")
    if "edit" in capabilities:
        tools.append("edit")
    if "web" in capabilities:
        tools.append("web")
    if agent["delegates_to"]:
        tools.append("agent")
    body, body_hash = _body_and_hash(root, agent)
    lines = [
        "---",
        f"{GENERATED_BANNER} from canonical/fleet.json and canonical/{agent['body']}; "
        f"body-sha256={body_hash}; DO NOT EDIT.",
        f"name: {agent['name']}",
        f"description: {json.dumps(agent['description'], ensure_ascii=False)}",
        f"tools: {_flow_list(tools)}",
    ]
    copilot_models = models["copilot"]
    if copilot_models:
        assert isinstance(copilot_models, list)
        lines.append(f"model: {_flow_list(copilot_models)}")
    if agent["delegates_to"]:
        lines.append(f"agents: {_flow_list(agent['delegates_to'])}")
    if agent["handoffs"]:
        lines.append("handoffs:")
        for handoff in agent["handoffs"]:
            lines.extend([
                f"  - agent: {handoff['agent']}",
                f"    label: {json.dumps(handoff['label'], ensure_ascii=False)}",
                f"    prompt: {json.dumps(handoff['prompt'], ensure_ascii=False)}",
                f"    send: {str(handoff['send']).lower()}",
            ])
    lines.extend(["---", body])
    return "\n".join(lines).encode("utf-8")


def _claude_agent(
    root: Path, agent: dict, models: dict[str, list[str] | str | None],
) -> bytes:
    capabilities = set(agent["capabilities"])
    tools: list[str] = []
    if "read" in capabilities:
        tools.append("Read")
    if "search" in capabilities:
        tools.extend(("Grep", "Glob"))
    if "execute" in capabilities:
        tools.append("Bash")
    if "edit" in capabilities:
        tools.extend(("Edit", "Write"))
    if "web" in capabilities:
        tools.extend(("WebSearch", "WebFetch"))
    if agent["skills"]:
        tools.append("Skill")
    if agent["delegates_to"]:
        tools.append(f"Agent({', '.join(agent['delegates_to'])})")
    body, body_hash = _body_and_hash(root, agent)
    lines = [
        "---",
        f"{GENERATED_BANNER} from canonical/fleet.json and canonical/{agent['body']}; "
        f"body-sha256={body_hash}; DO NOT EDIT.",
        f"name: {agent['name']}",
        f"description: {json.dumps(agent['description'], ensure_ascii=False)}",
        f"tools: {', '.join(tools)}",
    ]
    claude_model = models["claude"]
    if claude_model is not None:
        assert isinstance(claude_model, str)
        lines.append(f"model: {json.dumps(claude_model, ensure_ascii=False)}")
    lines.extend(["---", body])
    return "\n".join(lines).encode("utf-8")


def _plugin_manifest(manifest: dict, runtime: str) -> dict:
    plugin = manifest["plugin"]
    result = {
        "name": plugin["name"],
        "version": plugin["version"],
        "description": plugin["description"],
        "author": plugin["author"],
    }
    if manifest["agents"]:
        if runtime == "copilot":
            # Copilot's root manifest points at an agent directory.
            result["agents"] = "./generated/copilot/agents/"
        else:
            # Claude's strict schema requires explicit custom-agent file paths.
            result["agents"] = [
                f"./generated/claude/agents/{agent['name']}.md"
                for agent in manifest["agents"]
            ]
    else:
        # Both runtimes otherwise auto-discover their default agents/ directory.
        result["agents"] = []
    result["skills"] = "./skills/" if manifest["skills"] else []
    if manifest["commands"]:
        result["commands"] = (
            "./commands/"
            if runtime == "copilot"
            else [f"./{relative}" for relative in manifest["commands"]]
        )
    else:
        result["commands"] = []
    return result


def _copilot_hooks() -> dict:
    marker = "FORMAT_BOUNDARY_SESSION_START:copilot"
    code = (
        "python -c \"import json; print(json.dumps({'hookSpecificOutput': "
        "{'hookEventName': 'SessionStart', 'additionalContext': '" + marker + "'}}))\""
    )
    windows = code.replace("python -c", "py -3 -c", 1)
    posix = code.replace("python -c", "python3 -c", 1)
    return {
        "hooks": {
            "SessionStart": [{
                "type": "command",
                "command": posix,
                "windows": windows,
                "linux": posix,
                "osx": posix,
            }]
        }
    }


def _claude_hooks() -> dict:
    return {
        "hooks": {
            "SessionStart": [{
                "hooks": [{
                    "type": "command",
                    "command": "python",
                    "args": [
                        "${CLAUDE_PLUGIN_ROOT}/scripts/session_start_marker.py",
                        "claude",
                    ],
                }]
            }]
        }
    }


def _compatibility_report(manifest: dict) -> dict:
    copilot_manifest = _plugin_manifest(manifest, "copilot")
    claude_manifest = _plugin_manifest(manifest, "claude")
    claude_agent_paths = claude_manifest.get("agents", [])
    plugin_name = manifest["plugin"]["name"]
    skill_names = [skill["name"] for skill in manifest["skills"]]
    models = _validate_models(manifest)
    has_agents = bool(manifest["agents"])
    models_omitted = not models["copilot"] and models["claude"] is None
    return {
        "schema_version": 1,
        "generated_from": "canonical/fleet.json",
        "plugin_name": plugin_name,
        "canonical_agent_count": len(manifest["agents"]),
        "generated_wrapper_count": len(manifest["agents"]) * 2,
        "canonical_command_count": len(manifest["commands"]),
        "model_projection": {
            "spike": (
                "wrapper-model-fields-omitted-to-inherit-session-model"
                if models_omitted else "runtime-specific-canonical-policy"
            ),
            "copilot": {
                "shape": "list",
                "configured": models["copilot"],
                "emitted": has_agents and bool(models["copilot"]),
            },
            "claude": {
                "shape": "scalar",
                "configured": models["claude"],
                "emitted": has_agents and models["claude"] is not None,
            },
        },
        "copilot": {
            "agent_suffix": ".agent.md",
            "delegation_allowlist": "agents field plus agent tool",
            "agent_manifest_path_kind": (
                "directory" if has_agents else "explicit-empty-list"
            ),
            "agent_manifest_path": copilot_manifest.get("agents"),
            "skill_registered_names": skill_names,
        },
        "claude": {
            "agent_suffix": ".md",
            "delegation_tool": "Agent(type)",
            "agent_type_allowlist_enforced_when_main": True,
            "agent_type_list_ignored_when_nested": True,
            "agent_manifest_path_kind": (
                "file-list" if has_agents else "explicit-empty-list"
            ),
            "agent_manifest_paths": claude_agent_paths,
            "skill_registered_names": [
                f"{plugin_name}:{skill_name}" for skill_name in skill_names
            ],
        },
        "handoffs": "copilot-only",
        "plugin_agent_scoped_hooks_portable": False,
        "hook_projection": {
            "copilot": "root hooks.json; no plugin-root token, so the marker is inline",
            "claude": "hooks/hooks.json; helper resolved through ${CLAUDE_PLUGIN_ROOT}",
            "standard_path_auto_discovery": True,
            "manifest_hook_key_present": False,
        },
    }


def _session_marker_script() -> bytes:
    return b'''#!/usr/bin/env python3
# GENERATED by scripts/generate.py from canonical/fleet.json; DO NOT EDIT.
"""Emit inert SessionStart context for the format-boundary spike.

This helper performs no filesystem writes and makes no network calls. Its only
observable effect is a fixed JSON message on stdout for the invoking runtime.
"""

from __future__ import annotations

import argparse
import json

MARKER = "FORMAT_BOUNDARY_SESSION_START"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("runtime", choices=("claude", "copilot"))
    args = parser.parse_args()
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "SessionStart",
            "additionalContext": f"{MARKER}:{args.runtime}",
        }
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def render(root: Path) -> dict[Path, bytes]:
    manifest = load_manifest(root)
    models = _validate_models(manifest)
    files: dict[Path, bytes] = {
        Path("plugin.json"): _json_bytes(_plugin_manifest(manifest, "copilot")),
        Path(".claude-plugin/plugin.json"): _json_bytes(_plugin_manifest(manifest, "claude")),
        Path("hooks.json"): _json_bytes(_copilot_hooks()),
        Path("hooks/hooks.json"): _json_bytes(_claude_hooks()),
        Path("compatibility.json"): _json_bytes(_compatibility_report(manifest)),
        Path("scripts/session_start_marker.py"): _session_marker_script(),
    }
    for agent in manifest["agents"]:
        name = agent["name"]
        files[Path(f"generated/copilot/agents/{name}.agent.md")] = _copilot_agent(
            root, agent, models,
        )
        files[Path(f"generated/claude/agents/{name}.md")] = _claude_agent(
            root, agent, models,
        )
    return dict(sorted(files.items(), key=lambda item: item[0].as_posix()))


def compare_outputs(expected: dict[Path, bytes], actual: dict[Path, bytes]) -> list[str]:
    """Return deterministic missing/stale/unexpected projection diagnostics."""
    issues: list[str] = []
    for relative, content in expected.items():
        if relative not in actual:
            issues.append(f"missing generated file: {relative.as_posix()}")
        elif actual[relative] != content:
            issues.append(f"stale generated file: {relative.as_posix()}")
    for relative in sorted(set(actual) - set(expected), key=Path.as_posix):
        issues.append(f"unexpected generated file: {relative.as_posix()}")
    return issues


def _owned_wrapper_files(root: Path) -> dict[Path, Path]:
    owned: dict[Path, Path] = {}
    for relative_directory in OWNED_WRAPPER_DIRECTORIES:
        directory = root / relative_directory
        _require_safe_output_path(
            root, directory, operation="inspect", expected_kind="directory"
        )
        if not directory.is_dir():
            continue
        for candidate in _walk_tree_without_following_links(directory):
            if _is_link_or_junction(candidate):
                relative = candidate.relative_to(root)
                owned[relative] = candidate
            elif candidate.is_file() and candidate.name != ".gitkeep":
                relative = candidate.relative_to(root)
                owned[relative] = candidate
    return owned


def _require_safe_output_path(
    root: Path,
    target: Path,
    *,
    operation: str,
    expected_kind: str,
) -> None:
    try:
        relative = target.relative_to(root)
    except ValueError as exc:
        raise ManifestError(f"generated output escapes plugin root: {target}") from exc

    current = root
    for part in relative.parts[:-1]:
        current = current / part
        if _is_link_or_junction(current):
            raise ManifestError(
                f"refusing to {operation} through a link or junction parent: {current}"
            )
        if current.exists() and not current.is_dir():
            raise ManifestError(f"generated output parent is not a directory: {current}")

    if _is_link_or_junction(target):
        raise ManifestError(
            f"refusing to {operation} through a link or junction: {target}"
        )
    if target.exists():
        if expected_kind == "directory":
            if not target.is_dir():
                raise ManifestError(
                    f"generated wrapper path is not a directory: {target}"
                )
            return
        if expected_kind != "file":
            raise AssertionError(f"unsupported generated output kind: {expected_kind}")
        if not target.is_file():
            raise ManifestError(f"generated output is not a regular file: {target}")
        try:
            link_count = target.stat().st_nlink
        except OSError as exc:
            raise ManifestError(f"cannot inspect generated output: {target}") from exc
        if link_count > 1:
            raise ManifestError(f"refusing to overwrite hardlinked output: {target}")


def _require_safe_write_target(root: Path, target: Path) -> None:
    _require_safe_output_path(
        root, target, operation="write", expected_kind="file"
    )


def _require_safe_check_target(root: Path, target: Path) -> None:
    _require_safe_output_path(
        root, target, operation="inspect", expected_kind="file"
    )


def _atomic_write(root: Path, target: Path, content: bytes) -> None:
    _require_safe_write_target(root, target)
    target.parent.mkdir(parents=True, exist_ok=True)
    _require_safe_write_target(root, target)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=target.parent,
        prefix=f".{target.name}.",
        suffix=".tmp",
    )
    temporary_path = Path(temporary_name)
    try:
        stream = os.fdopen(descriptor, "wb")
        descriptor = -1
        with stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary_path, 0o644)
        _require_safe_output_path(
            root, temporary_path, operation="write", expected_kind="file"
        )
        _require_safe_write_target(root, target)
        os.replace(temporary_path, target)
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        try:
            os.unlink(temporary_path)
        except FileNotFoundError:
            pass


def check(root: Path) -> list[str]:
    expected = render(root)
    actual: dict[Path, bytes] = {}
    for relative in expected:
        target = root / relative
        _require_safe_check_target(root, target)
        if target.is_file():
            actual[relative] = target.read_bytes()
    for relative, target in _owned_wrapper_files(root).items():
        content = (
            b"<unsafe-link-or-junction>"
            if _is_link_or_junction(target)
            else target.read_bytes()
        )
        actual.setdefault(relative, content)
    return compare_outputs(expected, actual)


def write(root: Path) -> None:
    expected = render(root)
    for relative in expected:
        _require_safe_write_target(root, root / relative)
    owned = _owned_wrapper_files(root)
    for relative, target in owned.items():
        if relative not in expected:
            if _is_link_or_junction(target):
                raise ManifestError(
                    f"refusing to remove unsafe generated link or junction: {target}"
                )
            target.unlink()
    for relative, content in expected.items():
        target = root / relative
        _atomic_write(root, target, content)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail if projections differ")
    mode.add_argument("--write", action="store_true", help="regenerate projections")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    try:
        if args.write:
            write(root)
        issues = check(root)
    except ManifestError as exc:
        print(f"FORMAT PROJECTIONS: FAIL - {exc}", file=sys.stderr)
        return 1
    if issues:
        print("FORMAT PROJECTIONS: FAIL")
        for issue in issues:
            print(f"  - {issue}")
        if args.check:
            print("Run this script with --write, then review the generated diff.")
        return 1
    print(f"FORMAT PROJECTIONS: PASS - {len(render(root))} generated file(s) match canonical/fleet.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
