#!/usr/bin/env python3
"""Generate deterministic Copilot and Claude wrappers from one canonical fleet.

The generator is intentionally stdlib-only. Markdown bodies and the shared
skill are sources; runtime-specific frontmatter, manifests, hooks, and the
compatibility report are projections and must never be hand-edited.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


class ManifestError(ValueError):
    """The canonical spike manifest is invalid."""


NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
VERSION_RE = re.compile(r"^\d+\.\d+\.\d+$")
KNOWN_CAPABILITIES = frozenset({"delegate", "read", "search", "skill"})
TOP_KEYS = frozenset({"schema_version", "plugin", "skills", "agents"})
PLUGIN_KEYS = frozenset({"name", "version", "description", "author"})
AUTHOR_KEYS = frozenset({"name"})
SKILL_KEYS = frozenset({"name", "directory", "references"})
AGENT_KEYS = frozenset({
    "name", "description", "body", "capabilities", "skills", "delegates_to", "handoffs",
})
HANDOFF_KEYS = frozenset({"agent", "label", "prompt", "send"})
GENERATED_BANNER = "# GENERATED by scripts/generate.py"


def _unknown_keys(value: dict, known: frozenset[str], where: str) -> None:
    unknown = sorted(set(value) - known)
    if unknown:
        raise ManifestError(f"{where}: unknown {where} key(s): {', '.join(unknown)}")


def _require_string(value: object, where: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ManifestError(f"{where}: expected a non-empty string")
    return value


def _require_string_list(value: object, where: str) -> list[str]:
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise ManifestError(f"{where}: expected a list of strings")
    if len(value) != len(set(value)):
        raise ManifestError(f"{where}: duplicate values are not allowed")
    return value


def _source_path(root: Path, relative: str) -> Path:
    canonical = (root / "canonical").resolve()
    candidate = (canonical / relative).resolve()
    try:
        candidate.relative_to(canonical)
    except ValueError as exc:
        raise ManifestError(f"body path escapes canonical/: {relative}") from exc
    if not candidate.is_file():
        raise ManifestError(f"body path does not exist: {relative}")
    return candidate


def compare_skill_inventory(
    expected: dict[str, set[str]],
    actual_directories: set[str],
    actual_references: dict[str, set[str]],
) -> list[str]:
    """Compare canonical skill/reference inventory without touching the filesystem."""
    issues: list[str] = []
    expected_directories = set(expected)
    for directory in sorted(expected_directories - actual_directories):
        issues.append(f"missing runtime-visible skill directory: {directory}")
    for directory in sorted(actual_directories - expected_directories):
        issues.append(f"unexpected runtime-visible skill directory: {directory}")
    for directory in sorted(expected_directories & actual_directories):
        wanted = expected[directory]
        found = actual_references.get(directory, set())
        for reference in sorted(wanted - found):
            issues.append(f"skill '{directory}' missing inventoried reference: {reference}")
        for reference in sorted(found - wanted):
            issues.append(f"skill '{directory}' has unexpected runtime-visible reference: {reference}")
    return issues


def compare_agent_body_inventory(expected: set[str], actual: set[str]) -> list[str]:
    """Compare canonical agent-body paths without touching the filesystem."""
    issues: list[str] = []
    for body in sorted(expected - actual):
        issues.append(f"missing canonical agent body: {body}")
    for body in sorted(actual - expected):
        issues.append(f"unexpected canonical agent body: {body}")
    return issues


def _skill_frontmatter_name(text: str, path: Path) -> str:
    if not text.startswith("---"):
        raise ManifestError(f"skill has no YAML frontmatter: {path}")
    parts = text.split("---", 2)
    if len(parts) != 3:
        raise ManifestError(f"skill has unterminated YAML frontmatter: {path}")
    matches = re.findall(r"^name\s*:\s*([^\s#]+)\s*$", parts[1], re.MULTILINE)
    if len(matches) != 1:
        raise ManifestError(f"skill must declare exactly one frontmatter name: {path}")
    return matches[0]


def _linked_references(text: str) -> set[str]:
    links: set[str] = set()
    for match in re.finditer(r"\[[^\]]*\]\(([^)]+)\)", text):
        target = match.group(1).strip().split("#", 1)[0]
        if target.startswith("./"):
            target = target[2:]
        if target.startswith("references/"):
            links.add(Path(target).as_posix())
    return links


def compare_reference_links(
    skill_name: str, expected: set[str], linked: set[str],
) -> list[str]:
    """Compare canonical reference inventory with links from a SKILL body."""
    issues: list[str] = []
    missing = sorted(expected - linked)
    extra = sorted(linked - expected)
    if missing:
        issues.append(
            f"skill '{skill_name}' has unlinked inventoried references: {', '.join(missing)}"
        )
    if extra:
        issues.append(
            f"skill '{skill_name}' links un-inventoried references: {', '.join(extra)}"
        )
    return issues


def _validate_skills(manifest: dict, root: Path) -> set[str]:
    skills = manifest.get("skills")
    if not isinstance(skills, list) or not skills:
        raise ManifestError("skills: expected a non-empty list")
    expected_inventory: dict[str, set[str]] = {}
    skill_names: set[str] = set()
    for index, skill in enumerate(skills):
        where = f"skill[{index}]"
        if not isinstance(skill, dict):
            raise ManifestError(f"{where}: expected an object")
        _unknown_keys(skill, SKILL_KEYS, where)
        name = _require_string(skill.get("name"), f"{where}.name")
        if not NAME_RE.fullmatch(name):
            raise ManifestError(f"{where}.name must be kebab-case")
        if name in skill_names:
            raise ManifestError(f"duplicate canonical skill name: {name}")
        skill_names.add(name)
        directory_value = _require_string(skill.get("directory"), f"{where}.directory")
        directory = Path(directory_value)
        if directory.is_absolute() or ".." in directory.parts or len(directory.parts) != 2 \
                or directory.parts[0] != "skills":
            raise ManifestError(f"{where}.directory must be skills/<name>")
        if directory.name != name:
            raise ManifestError(
                f"{where}: skill name '{name}' does not match directory '{directory.name}'"
            )
        skill_dir = (root / directory).resolve()
        skills_root = (root / "skills").resolve()
        try:
            skill_dir.relative_to(skills_root)
        except ValueError as exc:
            raise ManifestError(f"{where}.directory escapes skills/: {directory_value}") from exc
        skill_file = skill_dir / "SKILL.md"
        if not skill_file.is_file():
            raise ManifestError(f"{where}: missing SKILL.md at {skill_file}")
        skill_text = skill_file.read_text(encoding="utf-8")
        frontmatter_name = _skill_frontmatter_name(skill_text, skill_file)
        if frontmatter_name != name:
            raise ManifestError(
                f"{where}: frontmatter name '{frontmatter_name}' does not match '{name}'"
            )
        references = _require_string_list(skill.get("references"), f"{where}.references")
        normalized: set[str] = set()
        for reference in references:
            path = Path(reference)
            if path.is_absolute() or ".." in path.parts or not path.parts \
                    or path.parts[0] != "references":
                raise ManifestError(f"{where}: invalid reference path '{reference}'")
            normalized.add(path.as_posix())
        linked = _linked_references(skill_text)
        link_problems = compare_reference_links(name, normalized, linked)
        if link_problems:
            raise ManifestError(f"{where}: reference link parity failed ({'; '.join(link_problems)})")
        expected_inventory[name] = normalized

    skills_root = root / "skills"
    actual_directories = {
        child.name for child in skills_root.iterdir() if child.is_dir()
    } if skills_root.is_dir() else set()
    actual_references: dict[str, set[str]] = {}
    for directory in actual_directories:
        reference_root = skills_root / directory / "references"
        actual_references[directory] = {
            file.relative_to(skills_root / directory).as_posix()
            for file in reference_root.rglob("*") if file.is_file()
        } if reference_root.is_dir() else set()
    inventory_problems = compare_skill_inventory(
        expected_inventory, actual_directories, actual_references,
    )
    if inventory_problems:
        raise ManifestError("; ".join(inventory_problems))
    return skill_names


def load_manifest(root: Path) -> dict:
    path = root / "canonical" / "fleet.json"
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ManifestError(f"canonical manifest missing: {path}") from exc
    except json.JSONDecodeError as exc:
        raise ManifestError(f"canonical manifest is invalid JSON: {exc}") from exc
    if not isinstance(value, dict):
        raise ManifestError("canonical manifest must be a JSON object")
    validate_manifest(value, root)
    return value


def validate_manifest(manifest: dict, root: Path) -> None:
    if not isinstance(manifest, dict):
        raise ManifestError("canonical manifest must be a JSON object")
    _unknown_keys(manifest, TOP_KEYS, "top-level")
    if manifest.get("schema_version") != 1:
        raise ManifestError("schema_version must be 1")

    plugin = manifest.get("plugin")
    if not isinstance(plugin, dict):
        raise ManifestError("plugin: expected an object")
    _unknown_keys(plugin, PLUGIN_KEYS, "plugin")
    plugin_name = _require_string(plugin.get("name"), "plugin.name")
    if not NAME_RE.fullmatch(plugin_name):
        raise ManifestError("plugin.name must be kebab-case")
    version = _require_string(plugin.get("version"), "plugin.version")
    if not VERSION_RE.fullmatch(version):
        raise ManifestError("plugin.version must be MAJOR.MINOR.PATCH")
    _require_string(plugin.get("description"), "plugin.description")
    author = plugin.get("author")
    if not isinstance(author, dict):
        raise ManifestError("plugin.author: expected an object")
    _unknown_keys(author, AUTHOR_KEYS, "author")
    _require_string(author.get("name"), "plugin.author.name")

    skill_names = _validate_skills(manifest, root)

    agents = manifest.get("agents")
    if not isinstance(agents, list) or not agents:
        raise ManifestError("agents: expected a non-empty list")

    names: list[str] = []
    expected_bodies: set[str] = set()
    for index, agent in enumerate(agents):
        where = f"agent[{index}]"
        if not isinstance(agent, dict):
            raise ManifestError(f"{where}: expected an object")
        unknown = sorted(set(agent) - AGENT_KEYS)
        if unknown:
            raise ManifestError(f"unknown agent key(s) in {where}: {', '.join(unknown)}")
        name = _require_string(agent.get("name"), f"{where}.name")
        if not NAME_RE.fullmatch(name):
            raise ManifestError(f"{where}.name must be kebab-case")
        names.append(name)
        _require_string(agent.get("description"), f"{where}.description")
        body = _require_string(agent.get("body"), f"{where}.body")
        normalized_body = Path(body).as_posix()
        required_body = f"agents/{name}.md"
        if normalized_body != required_body:
            raise ManifestError(
                f"{where}.body must be {required_body} for explicit agent name '{name}'"
            )
        _source_path(root, body)
        expected_bodies.add(normalized_body)
        capabilities = _require_string_list(agent.get("capabilities"), f"{where}.capabilities")
        for capability in capabilities:
            if capability not in KNOWN_CAPABILITIES:
                raise ManifestError(f"{where}: unknown capability '{capability}'")
        skill_dependencies = _require_string_list(agent.get("skills"), f"{where}.skills")
        unknown_dependencies = sorted(set(skill_dependencies) - skill_names)
        if unknown_dependencies:
            raise ManifestError(
                f"{where}: unknown skill dependency: {', '.join(unknown_dependencies)}"
            )
        if bool(skill_dependencies) != ("skill" in capabilities):
            raise ManifestError(
                f"{where}: capability 'skill' and a non-empty skills list must appear together"
            )
        delegates = _require_string_list(agent.get("delegates_to"), f"{where}.delegates_to")
        if bool(delegates) != ("delegate" in capabilities):
            raise ManifestError(
                f"{where}: capability 'delegate' and a non-empty delegates_to list must appear together"
            )
        handoffs = agent.get("handoffs")
        if not isinstance(handoffs, list):
            raise ManifestError(f"{where}.handoffs: expected a list")
        for handoff_index, handoff in enumerate(handoffs):
            hwhere = f"{where}.handoffs[{handoff_index}]"
            if not isinstance(handoff, dict):
                raise ManifestError(f"{hwhere}: expected an object")
            unknown_handoff = sorted(set(handoff) - HANDOFF_KEYS)
            if unknown_handoff:
                raise ManifestError(f"{hwhere}: unknown key(s): {', '.join(unknown_handoff)}")
            _require_string(handoff.get("agent"), f"{hwhere}.agent")
            _require_string(handoff.get("label"), f"{hwhere}.label")
            _require_string(handoff.get("prompt"), f"{hwhere}.prompt")
            if not isinstance(handoff.get("send"), bool):
                raise ManifestError(f"{hwhere}.send: expected a boolean")

    if len(names) != len(set(names)):
        raise ManifestError("agent names must be unique")
    agents_root = root / "canonical" / "agents"
    actual_bodies = {
        path.relative_to(root / "canonical").as_posix()
        for path in agents_root.rglob("*.md") if path.is_file()
    } if agents_root.is_dir() else set()
    body_inventory_problems = compare_agent_body_inventory(expected_bodies, actual_bodies)
    if body_inventory_problems:
        raise ManifestError("; ".join(body_inventory_problems))
    known_names = set(names)
    for agent in agents:
        name = agent["name"]
        for target in agent["delegates_to"]:
            if target not in known_names:
                raise ManifestError(f"agent '{name}' delegates to unknown agent '{target}'")
            if target == name:
                raise ManifestError(f"agent '{name}' cannot delegate to itself")
        for handoff in agent["handoffs"]:
            if handoff["agent"] not in known_names:
                raise ManifestError(
                    f"agent '{name}' hands off to unknown agent '{handoff['agent']}'"
                )


def _json_bytes(value: object) -> bytes:
    return (json.dumps(value, indent=2, ensure_ascii=False) + "\n").encode("utf-8")


def _flow_list(values: list[str]) -> str:
    return "[" + ", ".join("'" + value.replace("'", "''") + "'" for value in values) + "]"


def _body_and_hash(root: Path, agent: dict) -> tuple[str, str]:
    body = _source_path(root, agent["body"]).read_text(encoding="utf-8")
    if not body.endswith("\n"):
        body += "\n"
    return body, hashlib.sha256(body.encode("utf-8")).hexdigest()


def _copilot_agent(root: Path, agent: dict) -> bytes:
    capabilities = set(agent["capabilities"])
    tools: list[str] = []
    if "read" in capabilities:
        tools.append("read")
    if "search" in capabilities:
        tools.append("search")
    if "delegate" in capabilities:
        tools.append("agent")
    body, body_hash = _body_and_hash(root, agent)
    lines = [
        "---",
        f"{GENERATED_BANNER} from canonical/fleet.json and canonical/{agent['body']}; "
        f"body-sha256={body_hash}; DO NOT EDIT.",
        f"name: {agent['name']}",
        f"description: {json.dumps(agent['description'], ensure_ascii=False)}",
        f"tools: {_flow_list(tools)}",
    ]
    if agent["delegates_to"]:
        lines.append(f"agents: {_flow_list(agent['delegates_to'])}")
    if agent["handoffs"]:
        lines.append("handoffs:")
        for handoff in agent["handoffs"]:
            lines.extend([
                f"  - agent: {handoff['agent']}",
                f"    label: {json.dumps(handoff['label'], ensure_ascii=False)}",
                f"    prompt: {json.dumps(handoff['prompt'], ensure_ascii=False)}",
                f"    send: {str(handoff['send']).lower()}",
            ])
    lines.extend(["---", body])
    return "\n".join(lines).encode("utf-8")


def _claude_agent(root: Path, agent: dict) -> bytes:
    capabilities = set(agent["capabilities"])
    tools: list[str] = []
    if "read" in capabilities:
        tools.append("Read")
    if "search" in capabilities:
        tools.extend(("Grep", "Glob"))
    if "skill" in capabilities:
        tools.append("Skill")
    if "delegate" in capabilities:
        tools.append(f"Agent({', '.join(agent['delegates_to'])})")
    body, body_hash = _body_and_hash(root, agent)
    lines = [
        "---",
        f"{GENERATED_BANNER} from canonical/fleet.json and canonical/{agent['body']}; "
        f"body-sha256={body_hash}; DO NOT EDIT.",
        f"name: {agent['name']}",
        f"description: {json.dumps(agent['description'], ensure_ascii=False)}",
        f"tools: {', '.join(tools)}",
        "---",
        body,
    ]
    return "\n".join(lines).encode("utf-8")


def _plugin_manifest(manifest: dict, runtime: str) -> dict:
    plugin = manifest["plugin"]
    suffix = ".agent.md" if runtime == "copilot" else ".md"
    explicit_agent_paths = [
        f"./generated/{runtime}/agents/{agent['name']}{suffix}"
        for agent in manifest["agents"]
    ]
    agent_paths: str | list[str]
    if runtime == "copilot":
        # Copilot's root manifest points at an agent directory.
        agent_paths = "./generated/copilot/agents/"
    else:
        # Claude's strict schema requires explicit custom-agent file paths.
        agent_paths = explicit_agent_paths
    return {
        "name": plugin["name"],
        "version": plugin["version"],
        "description": plugin["description"],
        "author": plugin["author"],
        "agents": agent_paths,
        "skills": "./skills/",
    }


def _copilot_hooks() -> dict:
    marker = "FORMAT_BOUNDARY_SESSION_START:copilot"
    code = (
        "python -c \"import json; print(json.dumps({'hookSpecificOutput': "
        "{'hookEventName': 'SessionStart', 'additionalContext': '" + marker + "'}}))\""
    )
    windows = code.replace("python -c", "py -3 -c", 1)
    posix = code.replace("python -c", "python3 -c", 1)
    return {
        "hooks": {
            "SessionStart": [{
                "type": "command",
                "command": posix,
                "windows": windows,
                "linux": posix,
                "osx": posix,
            }]
        }
    }


def _claude_hooks() -> dict:
    return {
        "hooks": {
            "SessionStart": [{
                "hooks": [{
                    "type": "command",
                    "command": "python",
                    "args": [
                        "${CLAUDE_PLUGIN_ROOT}/scripts/session_start_marker.py",
                        "claude",
                    ],
                }]
            }]
        }
    }


def _compatibility_report(manifest: dict) -> dict:
    claude_agent_paths = _plugin_manifest(manifest, "claude")["agents"]
    plugin_name = manifest["plugin"]["name"]
    skill_names = [skill["name"] for skill in manifest["skills"]]
    return {
        "schema_version": 1,
        "generated_from": "canonical/fleet.json",
        "plugin_name": plugin_name,
        "two_agent_wrappers_required": True,
        "model_projection": {
            "spike": "omitted-to-inherit-session-model",
            "production_mapping": "separately generator-tested and runtime-probed",
        },
        "copilot": {
            "agent_suffix": ".agent.md",
            "delegation_allowlist": "agents field plus agent tool",
            "agent_manifest_path_kind": "directory",
            "agent_manifest_path": "./generated/copilot/agents/",
            "skill_registered_names": skill_names,
        },
        "claude": {
            "agent_suffix": ".md",
            "delegation_tool": "Agent(type)",
            "agent_type_allowlist_enforced_when_main": True,
            "agent_type_list_ignored_when_nested": True,
            "agent_manifest_path_kind": "file-list",
            "agent_manifest_paths": claude_agent_paths,
            "skill_registered_names": [
                f"{plugin_name}:{skill_name}" for skill_name in skill_names
            ],
        },
        "handoffs": "copilot-only",
        "plugin_agent_scoped_hooks_portable": False,
        "hook_projection": {
            "copilot": "root hooks.json; no plugin-root token, so the marker is inline",
            "claude": "hooks/hooks.json; helper resolved through ${CLAUDE_PLUGIN_ROOT}",
            "standard_path_auto_discovery": True,
            "manifest_hook_key_present": False,
        },
    }


def _session_marker_script() -> bytes:
    return b'''#!/usr/bin/env python3
# GENERATED by scripts/generate.py from canonical/fleet.json; DO NOT EDIT.
"""Emit inert SessionStart context for the format-boundary spike.

This helper performs no filesystem writes and makes no network calls. Its only
observable effect is a fixed JSON message on stdout for the invoking runtime.
"""

from __future__ import annotations

import argparse
import json

MARKER = "FORMAT_BOUNDARY_SESSION_START"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("runtime", choices=("claude", "copilot"))
    args = parser.parse_args()
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "SessionStart",
            "additionalContext": f"{MARKER}:{args.runtime}",
        }
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def render(root: Path) -> dict[Path, bytes]:
    manifest = load_manifest(root)
    files: dict[Path, bytes] = {
        Path("plugin.json"): _json_bytes(_plugin_manifest(manifest, "copilot")),
        Path(".claude-plugin/plugin.json"): _json_bytes(_plugin_manifest(manifest, "claude")),
        Path("hooks.json"): _json_bytes(_copilot_hooks()),
        Path("hooks/hooks.json"): _json_bytes(_claude_hooks()),
        Path("compatibility.json"): _json_bytes(_compatibility_report(manifest)),
        Path("scripts/session_start_marker.py"): _session_marker_script(),
    }
    for agent in manifest["agents"]:
        name = agent["name"]
        files[Path(f"generated/copilot/agents/{name}.agent.md")] = _copilot_agent(root, agent)
        files[Path(f"generated/claude/agents/{name}.md")] = _claude_agent(root, agent)
    return dict(sorted(files.items(), key=lambda item: item[0].as_posix()))


def compare_outputs(expected: dict[Path, bytes], actual: dict[Path, bytes]) -> list[str]:
    """Return deterministic missing/stale/unexpected projection diagnostics."""
    issues: list[str] = []
    for relative, content in expected.items():
        if relative not in actual:
            issues.append(f"missing generated file: {relative.as_posix()}")
        elif actual[relative] != content:
            issues.append(f"stale generated file: {relative.as_posix()}")
    for relative in sorted(set(actual) - set(expected), key=Path.as_posix):
        issues.append(f"unexpected generated file: {relative.as_posix()}")
    return issues


def check(root: Path) -> list[str]:
    expected = render(root)
    actual: dict[Path, bytes] = {}
    for relative in expected:
        target = root / relative
        if target.is_file():
            actual[relative] = target.read_bytes()
    for directory, pattern in (
        (root / "generated" / "copilot" / "agents", "*.agent.md"),
        (root / "generated" / "claude" / "agents", "*.md"),
    ):
        if directory.is_dir():
            for target in directory.glob(pattern):
                relative = target.relative_to(root)
                actual.setdefault(relative, target.read_bytes())
    return compare_outputs(expected, actual)


def write(root: Path) -> None:
    expected = render(root)
    for relative, content in expected.items():
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail if projections differ")
    mode.add_argument("--write", action="store_true", help="regenerate projections")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    try:
        if args.write:
            write(root)
        issues = check(root)
    except ManifestError as exc:
        print(f"FORMAT PROJECTIONS: FAIL - {exc}", file=sys.stderr)
        return 1
    if issues:
        print("FORMAT PROJECTIONS: FAIL")
        for issue in issues:
            print(f"  - {issue}")
        if args.check:
            print("Run this script with --write, then review the generated diff.")
        return 1
    print(f"FORMAT PROJECTIONS: PASS - {len(render(root))} generated file(s) match canonical/fleet.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
