#!/usr/bin/env python3
# GENERATED by scripts/generate.py from canonical/fleet.json; DO NOT EDIT.
"""Emit inert SessionStart context for the format-boundary spike.

This helper performs no filesystem writes and makes no network calls. Its only
observable effect is a fixed JSON message on stdout for the invoking runtime.
"""

from __future__ import annotations

import argparse
import json

MARKER = "FORMAT_BOUNDARY_SESSION_START"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("runtime", choices=("claude", "copilot"))
    args = parser.parse_args()
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "SessionStart",
            "additionalContext": f"{MARKER}:{args.runtime}",
        }
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
