#!/usr/bin/env python3
"""Generate drift-checked Copilot and Claude projections from canonical data.

Command projections are deterministic and byte-joined to their canonical body.
Their live runtime boundary remains [unverified] because Task-2b compatibility
evidence is absent under the user-authorized prerequisite override.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
import sys
import tempfile
from pathlib import Path, PurePosixPath


class ManifestError(ValueError):
    """Canonical input or an owned output path violates the fleet contract."""


NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
VERSION_RE = re.compile(r"^\d+\.\d+\.\d+$")
KNOWN_CAPABILITIES = frozenset({"read", "search", "execute", "edit", "web"})
TOP_KEYS = frozenset(
    {
        "schema_version",
        "plugin",
        "models",
        "assembly_state",
        "commands",
        "skills",
        "skill_dependencies",
        "agents",
    }
)
PLUGIN_KEYS = frozenset(
    {
        "name",
        "displayName",
        "description",
        "version",
        "author",
        "homepage",
        "repository",
        "license",
        "keywords",
    }
)
AUTHOR_KEYS = frozenset({"name", "url"})
MODEL_KEYS = frozenset({"copilot", "claude"})
AGENT_KEYS = frozenset(
    {
        "name",
        "description",
        "body",
        "capabilities",
        "required_skills",
        "delegates_to",
        "handoffs",
    }
)
HANDOFF_KEYS = frozenset({"agent", "label", "prompt", "send"})
COMMAND_KEYS = frozenset(
    {
        "name",
        "source",
        "description",
        "argument_mode",
        "argument_usage",
        "invocation_mode",
    }
)
BUNDLE_KINDS = ("references", "assets", "scripts")
PLANNED_SKILL_KEYS = frozenset({"name", "state", "activate_task"})
ACTIVE_SKILL_KEYS = frozenset(
    {"name", "state", "directory", "references", "assets", "scripts"}
)
ASSEMBLY_STATES = frozenset({"boundary-only", "content-building", "content-complete"})

PINNED_SKILLS = (
    ("stack-profile", 10),
    ("root-cause", 11),
    ("runbook", 12),
    ("eng-ladder", 13),
    ("craft", 14),
    ("backend-craft", 15),
    ("frontend-craft", 16),
    ("ops-tooling", 17),
    ("pcf-ops", 18),
    ("pcf-deploy", 18),
    ("database-reliability", 19),
    ("ci-actions", 20),
    ("merge-gate", 21),
    ("release-gate", 21),
    ("production-change-gate", 22),
    ("incident-command", 23),
    ("postmortem", 23),
    ("service-onboarding", 32),
    ("agent-authoring", 25),
    ("agent-security", 25),
    ("obs-logs", 27),
    ("obs-metrics", 28),
    ("obs-traces", 29),
    ("obs-dashboards", 30),
    ("obs-alerting", 31),
    ("obs-pipeline", 32),
)
PINNED_SKILL_DEPENDENCIES = {
    "ops-tooling": ["eng-ladder"],
    "service-onboarding": [
        "production-change-gate",
        "obs-pipeline",
        "obs-dashboards",
        "obs-alerting",
        "ci-actions",
        "runbook",
    ],
}
CONTENT_COMPLETE_AGENTS = ("reviewer", "sde", "sre", "observer", "scribe")
PINNED_AGENT_REQUIRED_SKILLS = {
    "reviewer": ["stack-profile"],
    "sde": [
        "stack-profile",
        "root-cause",
        "eng-ladder",
        "craft",
        "backend-craft",
        "frontend-craft",
    ],
    "sre": [
        "stack-profile",
        "root-cause",
        "eng-ladder",
        "pcf-ops",
        "database-reliability",
        "incident-command",
        "obs-logs",
        "obs-metrics",
        "obs-traces",
        "obs-dashboards",
        "obs-alerting",
    ],
    "observer": [
        "stack-profile",
        "obs-logs",
        "obs-metrics",
        "obs-traces",
        "obs-dashboards",
        "obs-alerting",
        "obs-pipeline",
    ],
    "scribe": ["stack-profile", "runbook", "postmortem"],
}

REQUIRED_START = "<!-- required-skills:start -->"
REQUIRED_END = "<!-- required-skills:end -->"
DEPENDENCY_START = "<!-- required-skill-dependencies:start -->"
DEPENDENCY_END = "<!-- required-skill-dependencies:end -->"
REQUIRED_LINE = re.compile(
    r"^- `(?P<copilot>[a-z0-9-]+)` "
    r"\(Claude: `sre-agents:(?P<claude>[a-z0-9-]+)`\) — \S.*$"
)
DEPENDENCY_LINE = re.compile(
    r"^- canonical `(?P<canonical>[a-z0-9-]+)`; "
    r"Copilot `(?P<copilot>[a-z0-9-]+)`; "
    r"Claude `sre-agents:(?P<claude>[a-z0-9-]+)`$"
)
OWNER_LOAD_PAIR = re.compile(
    r"^load the owner: copilot `(?P<copilot>[a-z0-9-]+)`; "
    r"claude `sre-agents:(?P<claude>[a-z0-9-]+)`$"
)
MANUAL_ONLY_SKILLS = frozenset({"pcf-deploy", "service-onboarding"})
ACTION_STEMS = (
    "load",
    "invoke",
    "read",
    "use this skill",
    "see",
    "consult",
    "follow",
    "switch to",
)
MARKDOWN_LINK = re.compile(r"\[[^\]]+\]\((?P<path>[^)]+)\)")

GENERATED_BANNER = "# GENERATED by scripts/generate_fleet.py"
ARGUMENT_SENTINEL = "{{arguments}}"
# [unverified: Task-2b prerequisite override] These documented runtime shapes
# are structurally tested here; Task 26 owns the first live production proof.
COMMAND_ARGUMENT_EXPRESSIONS = {
    "copilot": "$ARGUMENTS",
    "fallback": "${input:arguments}",
    "claude": "$ARGUMENTS",
}
# [unverified: Task-2b prerequisite override] Reject every documented native
# interpolation shape so canonical bodies keep one input channel only.
RUNTIME_INTERPOLATION = re.compile(
    r"\$(?:ARGUMENTS(?:\[[0-9]+\])?|[0-9]+|\{[^}\r\n]+\})"
)
OWNED_DIRECTORIES = (
    Path("generated/copilot/agents"),
    Path("generated/claude/agents"),
    Path("generated/copilot/commands"),
    Path("generated/copilot/prompts"),
    Path("generated/claude/commands"),
)
ROOT_OUTPUTS = (
    Path("plugin.json"),
    Path(".claude-plugin/plugin.json"),
    Path("hooks.json"),
    Path("hooks/hooks.json"),
)
DEFAULT_DISCOVERY_TREES = (
    Path("agents"),
    Path("commands"),
    Path(".agents"),
    Path(".github/agents"),
    Path(".github/prompts"),
    Path(".github/skills"),
    Path(".claude/agents"),
    Path(".claude/commands"),
    Path(".claude/skills"),
)


def _reject_duplicate_json_keys(pairs: list[tuple[str, object]]) -> dict:
    result: dict = {}
    for key, value in pairs:
        if key in result:
            raise ManifestError(f"canonical manifest has duplicate JSON key: {key}")
        result[key] = value
    return result


def _unknown_keys(value: object, known: frozenset[str], where: str) -> dict:
    if not isinstance(value, dict):
        raise ManifestError(f"{where}: expected an object")
    unknown = sorted(set(value) - known)
    if unknown:
        raise ManifestError(f"{where}: unknown key(s): {', '.join(unknown)}")
    return value


def _require_string(value: object, where: str) -> str:
    if (
        not isinstance(value, str)
        or not value
        or value != value.strip()
        or "\n" in value
        or "\r" in value
        or not value.isprintable()
    ):
        raise ManifestError(f"{where}: expected trimmed single-line printable text")
    return value


def _require_string_list(value: object, where: str) -> list[str]:
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise ManifestError(f"{where}: expected a list of strings")
    if len(value) != len(set(value)):
        raise ManifestError(f"{where}: duplicate values are not allowed")
    return value


def _is_link_or_junction(path: Path) -> bool:
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        return False
    except OSError as exc:
        raise ManifestError(f"cannot inspect path: {path}") from exc
    if stat.S_ISLNK(metadata.st_mode):
        return True
    attributes = getattr(metadata, "st_file_attributes", 0)
    reparse = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    return bool(attributes & reparse)


def _is_hardlinked_file(path: Path) -> bool:
    try:
        metadata = path.stat()
    except FileNotFoundError:
        return False
    except OSError as exc:
        raise ManifestError(f"cannot inspect hardlink count: {path}") from exc
    return stat.S_ISREG(metadata.st_mode) and metadata.st_nlink != 1


def _require_root(root: Path) -> Path:
    root = root.absolute()
    if _is_link_or_junction(root):
        raise ManifestError(f"fleet root cannot be a link or junction: {root}")
    if not root.is_dir():
        raise ManifestError(f"fleet root must be a directory: {root}")
    return root


def _require_contained(path: Path, root: Path, where: str, *, exists: bool = True) -> None:
    root = root.absolute()
    path = path.absolute()
    try:
        relative = path.relative_to(root)
    except ValueError as exc:
        raise ManifestError(f"{where}: path escapes owned root: {path}") from exc
    current = root
    for part in relative.parts:
        current = current / part
        if _is_link_or_junction(current):
            raise ManifestError(f"{where}: link or junction is not allowed: {current}")
        if not current.exists():
            if exists:
                raise ManifestError(f"{where}: missing path: {current}")
            break
    if exists:
        try:
            path.resolve(strict=True).relative_to(root.resolve(strict=True))
        except (OSError, ValueError) as exc:
            raise ManifestError(f"{where}: path escapes owned root: {path}") from exc


def _walk_no_links(root: Path):
    if _is_link_or_junction(root):
        raise ManifestError(f"link or junction is not allowed: {root}")
    if not root.exists():
        return
    if not root.is_dir():
        raise ManifestError(f"expected directory: {root}")
    for current, directory_names, file_names in os.walk(root, topdown=True, followlinks=False):
        current_path = Path(current)
        safe_directories: list[str] = []
        for name in sorted(directory_names):
            candidate = current_path / name
            yield candidate
            if _is_link_or_junction(candidate):
                raise ManifestError(f"link or junction is not allowed: {candidate}")
            safe_directories.append(name)
        directory_names[:] = safe_directories
        for name in sorted(file_names):
            candidate = current_path / name
            if _is_link_or_junction(candidate):
                raise ManifestError(f"link or junction is not allowed: {candidate}")
            yield candidate


def _normalize_posix_path(value: object, where: str, *, prefix: str | None = None) -> str:
    raw = _require_string(value, where)
    pure = PurePosixPath(raw)
    if (
        "\\" in raw
        or pure.is_absolute()
        or ".." in pure.parts
        or pure.as_posix() != raw
        or (prefix is not None and (len(pure.parts) < 2 or pure.parts[0] != prefix))
    ):
        raise ManifestError(f"{where}: invalid POSIX-relative path: {raw}")
    return raw


def _validate_default_discovery(root: Path) -> None:
    root_skill = root / "SKILL.md"
    if root_skill.exists() or _is_link_or_junction(root_skill):
        raise ManifestError("unexpected root SKILL.md bypasses canonical skill inventory")
    for relative in DEFAULT_DISCOVERY_TREES:
        tree = root / relative
        if not tree.exists() and not _is_link_or_junction(tree):
            continue
        for candidate in _walk_no_links(tree):
            if candidate.is_file():
                raise ManifestError(
                    "unexpected default-discovery content bypasses canonical inventory: "
                    f"{candidate.relative_to(root).as_posix()}"
                )


def _validate_models(manifest: dict) -> dict[str, list[str] | str | None]:
    models = _unknown_keys(manifest.get("models"), MODEL_KEYS, "models")
    missing = MODEL_KEYS - set(models)
    if missing:
        raise ManifestError(f"models: missing key(s): {', '.join(sorted(missing))}")
    copilot = _require_string_list(models["copilot"], "models.copilot")
    for index, model in enumerate(copilot):
        _require_string(model, f"models.copilot[{index}]")
    claude = models["claude"]
    if claude is not None:
        _require_string(claude, "models.claude")
    return {"copilot": copilot, "claude": claude}


def _validate_plugin(manifest: dict) -> None:
    plugin = _unknown_keys(manifest.get("plugin"), PLUGIN_KEYS, "plugin")
    missing = PLUGIN_KEYS - set(plugin)
    if missing:
        raise ManifestError(f"plugin: missing key(s): {', '.join(sorted(missing))}")
    for key in PLUGIN_KEYS - {"author", "keywords"}:
        _require_string(plugin[key], f"plugin.{key}")
    if not NAME_RE.fullmatch(plugin["name"]):
        raise ManifestError("plugin.name: expected kebab-case")
    if not VERSION_RE.fullmatch(plugin["version"]):
        raise ManifestError("plugin.version: expected semantic x.y.z")
    author = _unknown_keys(plugin["author"], AUTHOR_KEYS, "plugin.author")
    if set(author) != AUTHOR_KEYS:
        raise ManifestError("plugin.author: exact name/url keys are required")
    _require_string(author["name"], "plugin.author.name")
    _require_string(author["url"], "plugin.author.url")
    keywords = _require_string_list(plugin["keywords"], "plugin.keywords")
    if not keywords:
        raise ManifestError("plugin.keywords: at least one keyword is required")
    for index, keyword in enumerate(keywords):
        _require_string(keyword, f"plugin.keywords[{index}]")


def _skill_frontmatter_fields(text: str, path: Path) -> dict[str, list[str]]:
    if not text.startswith("---\n"):
        raise ManifestError(f"skill frontmatter missing: {path}")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ManifestError(f"skill frontmatter is not closed: {path}")
    fields: dict[str, list[str]] = {}
    for line in text[4:end].splitlines():
        if not line or line.startswith((" ", "\t", "#")):
            continue
        match = re.fullmatch(r"([A-Za-z][A-Za-z0-9-]*):(?:[ \t]*(.*))?", line)
        if match is not None:
            fields.setdefault(match.group(1), []).append((match.group(2) or "").strip())
    return fields


def _validate_skill_frontmatter_controls(text: str, path: Path, name: str) -> None:
    fields = _skill_frontmatter_fields(text, path)
    names = fields.get("name", [])
    if len(names) != 1:
        raise ManifestError(f"skill frontmatter must contain one name: {path}")
    if names[0] != name:
        raise ManifestError(f"skill '{name}': frontmatter name does not match inventory")

    manual_values = fields.get("disable-model-invocation", [])
    if name in MANUAL_ONLY_SKILLS:
        if manual_values != ["true"]:
            raise ManifestError(
                f"skill '{name}': frontmatter must contain disable-model-invocation: true"
            )
    elif manual_values:
        raise ManifestError(
            "only pcf-deploy and service-onboarding may disable model invocation"
        )


def _block(text: str, start: str, end: str, where: str) -> tuple[str, str]:
    if text.count(start) != 1 or text.count(end) != 1:
        raise ManifestError(f"{where}: missing or duplicate dependency block marker")
    start_at = text.index(start)
    end_at = text.index(end)
    if start_at >= end_at:
        raise ManifestError(f"{where}: dependency block markers are reversed")
    inside = text[start_at + len(start) : end_at]
    outside = text[:start_at] + text[end_at + len(end) :]
    return inside, outside


def _action_targets(line: str, catalog: tuple[str, ...], *, owner: str | None = None) -> list[str]:
    lowered = line.lower()
    targets: list[str] = []

    def has_action(value: str) -> bool:
        return any(
            re.search(rf"\b{re.escape(stem)}(?=\s)", value)
            for stem in ACTION_STEMS
        )

    for target in catalog:
        if target == owner:
            continue
        search_from = 0
        while True:
            target_at = lowered.find(target, search_from)
            if target_at < 0:
                break
            prefix = lowered[:target_at]
            suffix = lowered[target_at + len(target) :]
            prefix_sentence = re.split(r"[.!?]", prefix)[-1]
            suffix_sentence = re.split(r"[.!?]", suffix, maxsplit=1)[0]
            parenthetical = re.match(r"\s*\((?P<body>[^)]*)\)", suffix_sentence)
            if parenthetical is not None:
                nested = parenthetical.group("body")
                owner_pair = OWNER_LOAD_PAIR.fullmatch(nested)
                paired_target = (
                    owner_pair.group("copilot") if owner_pair is not None else None
                )
                exact_different_owner = (
                    owner_pair is not None
                    and paired_target == owner_pair.group("claude")
                    and paired_target in catalog
                    and paired_target != target
                )
                if exact_different_owner:
                    # "link to a runbook (load the alerting owner: ...)" loads the
                    # exact paired owner, not the noun before the parenthesis. Any
                    # extra text/action makes the full match fail closed.
                    suffix_sentence = suffix_sentence[parenthetical.end() :]
            qualifier_at = prefix_sentence.rfind("not a load")
            qualifier_tail = (
                prefix_sentence[qualifier_at + len("not a load") :]
                if qualifier_at >= 0
                else ""
            )
            qualifier_head = prefix_sentence[:qualifier_at] if qualifier_at >= 0 else ""
            qualified_non_action = (
                qualifier_at >= 0
                and re.search(r"\b(?:ownership|handoff)\b", qualifier_head)
                and not has_action(qualifier_tail)
                and not any(candidate in qualifier_tail for candidate in catalog)
            )
            coreference_action = re.search(
                r"(?:[.,;!?]\s*|\b(?:then|but|and|so)\s+|\bhowever,?\s+)"
                r"(?:load|invoke|read|use|see|consult|follow|switch\s+to)\s+it\b",
                suffix,
            )
            if (
                (not qualified_non_action and has_action(prefix_sentence))
                or (not qualified_non_action and has_action(suffix_sentence))
                or coreference_action
            ):
                targets.append(target)
                break
            search_from = target_at + len(target)
    return targets


def _instruction_contexts(text: str) -> list[tuple[int, str]]:
    """Join wrapped guidance without widening across Markdown block boundaries."""
    contexts: list[tuple[int, str]] = []
    buffered: list[str] = []
    start_line = 0
    in_fence = False

    def flush() -> None:
        nonlocal buffered, start_line
        if buffered:
            contexts.append((start_line, " ".join(buffered)))
            buffered = []
            start_line = 0

    for line_number, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if re.match(r"^(?:```|~~~)", stripped):
            flush()
            in_fence = not in_fence
            continue
        if not stripped:
            flush()
            continue
        if not in_fence and stripped in {"---", "..."}:
            flush()
            continue
        if not in_fence and re.match(r"^#{1,6}\s", stripped):
            flush()
            contexts.append((line_number, stripped))
            continue
        if not in_fence and re.match(r"^(?:[-*+]|\d+[.)])\s+", line):
            flush()
            buffered = [stripped]
            start_line = line_number
            continue
        if not buffered:
            start_line = line_number
        buffered.append(stripped)
    flush()
    return contexts


def _validate_dependency_identities(text: str, owner: str, targets: list[str]) -> str:
    if not targets:
        if DEPENDENCY_START in text or DEPENDENCY_END in text:
            raise ManifestError(f"skill '{owner}': unexpected dependency identities block")
        return text
    inside, outside = _block(
        text, DEPENDENCY_START, DEPENDENCY_END, f"skill '{owner}' dependency identities"
    )
    triples: list[tuple[str, str, str]] = []
    for line in inside.splitlines():
        if not line.startswith("- "):
            continue
        match = DEPENDENCY_LINE.fullmatch(line)
        if match is None:
            raise ManifestError(f"skill '{owner}': malformed dependency identities line: {line}")
        triples.append(
            (match.group("canonical"), match.group("copilot"), match.group("claude"))
        )
    expected = [(target, target, target) for target in targets]
    if triples != expected:
        raise ManifestError(f"skill '{owner}': dependency identities do not match canonical graph")
    return outside


def _linked_paths(text: str) -> set[str]:
    result: set[str] = set()
    for match in MARKDOWN_LINK.finditer(text):
        value = match.group("path").split("#", 1)[0]
        if value.startswith("./"):
            value = value[2:]
        result.add(value)
    return result


def _validate_active_skill(
    root: Path,
    record: dict,
    active_names: set[str],
    catalog: tuple[str, ...],
    dependencies: dict[str, list[str]],
) -> None:
    name = record["name"]
    skill_root = root / record["directory"]
    _require_contained(skill_root, root / "skills", f"skill '{name}'")
    if not skill_root.is_dir():
        raise ManifestError(f"active skill directory is missing: {record['directory']}")

    expected_files = {"SKILL.md"}
    for kind in BUNDLE_KINDS:
        values = _require_string_list(record[kind], f"skill '{name}'.{kind}")
        normalized = [_normalize_posix_path(value, f"skill '{name}'.{kind}", prefix=kind) for value in values]
        if normalized != values:
            raise ManifestError(f"skill '{name}'.{kind}: inventory order drifted")
        expected_files.update(normalized)

    actual_files: set[str] = set()
    for candidate in _walk_no_links(skill_root):
        if candidate.is_file():
            _require_contained(candidate, skill_root, f"skill '{name}' inventory")
            actual_files.add(candidate.relative_to(skill_root).as_posix())
        elif candidate.is_dir():
            relative = candidate.relative_to(skill_root)
            if relative.parts and relative.parts[0] not in BUNDLE_KINDS:
                raise ManifestError(f"skill '{name}': unexpected directory {relative.as_posix()}")
    missing = sorted(expected_files - actual_files)
    unexpected = sorted(actual_files - expected_files)
    if missing:
        raise ManifestError(f"skill '{name}': missing inventoried file(s): {', '.join(missing)}")
    if unexpected:
        raise ManifestError(f"skill '{name}': unexpected file(s): {', '.join(unexpected)}")

    skill_path = skill_root / "SKILL.md"
    try:
        skill_text = skill_path.read_text(encoding="utf-8")
    except UnicodeError as exc:
        raise ManifestError(f"skill '{name}' SKILL.md must be UTF-8") from exc
    _validate_skill_frontmatter_controls(skill_text, skill_path, name)

    targets = dependencies.get(name, [])
    planned_targets = [target for target in targets if target not in active_names]
    if planned_targets:
        raise ManifestError(
            f"active skill '{name}' has planned target(s): {', '.join(planned_targets)}"
        )
    scan_skill_text = _validate_dependency_identities(skill_text, name, targets)
    linked = _linked_paths(skill_text)

    for relative in sorted(actual_files):
        path = skill_root / PurePosixPath(relative)
        if _is_hardlinked_file(path):
            raise ManifestError(f"skill '{name}': inventoried file is a hardlink: {relative}")
        raw = path.read_bytes()
        try:
            decoded = raw.decode("utf-8")
        except UnicodeDecodeError:
            if relative in linked:
                action_link = any(
                    relative in line and any(
                        re.search(rf"\b{re.escape(stem)}(?=\s)", line.lower())
                        for stem in ACTION_STEMS
                    )
                    for line in skill_text.splitlines()
                )
                if action_link:
                    raise ManifestError(
                        f"skill '{name}': binary instruction guidance is not allowed: {relative}"
                    )
            continue
        if relative == "SKILL.md":
            decoded = scan_skill_text
        for line_number, context in _instruction_contexts(decoded):
            for target in _action_targets(context, catalog, owner=name):
                if target not in targets:
                    raise ManifestError(
                        f"skill '{name}' {relative}:{line_number}: undeclared mandatory load '{target}'"
                    )
                paired = (
                    f"`{target}`" in context and f"`sre-agents:{target}`" in context
                )
                block_directed = (
                    "dependency block" in context.lower()
                    or "required-skill-dependencies" in context.lower()
                )
                if not paired and not block_directed:
                    raise ManifestError(
                        f"skill '{name}' {relative}:{line_number}: mandatory load lacks both runtime identities"
                    )


def _validate_skills(
    manifest: dict, root: Path
) -> tuple[set[str], dict[str, dict]]:
    skills = manifest.get("skills")
    if not isinstance(skills, list):
        raise ManifestError("skills: expected a list")
    if len(skills) != len(PINNED_SKILLS):
        raise ManifestError("skill catalog must contain exactly 26 pinned records")
    expected_names = tuple(name for name, _task in PINNED_SKILLS)
    records: dict[str, dict] = {}
    active_names: set[str] = set()
    for index, ((expected_name, expected_task), raw_record) in enumerate(
        zip(PINNED_SKILLS, skills, strict=True)
    ):
        if not isinstance(raw_record, dict):
            raise ManifestError(f"skill catalog[{index}]: expected an object")
        name = raw_record.get("name")
        if name != expected_name:
            raise ManifestError(
                f"skill catalog drifted at index {index}: expected {expected_name}, got {name}"
            )
        if name in records:
            raise ManifestError(f"skill catalog contains duplicate name: {name}")
        state = raw_record.get("state")
        if state == "planned":
            if set(raw_record) != PLANNED_SKILL_KEYS:
                raise ManifestError(f"planned skill '{name}' has invalid key shape")
            if raw_record.get("activate_task") != expected_task:
                raise ManifestError(f"skill catalog '{name}' activation task drifted")
        elif state == "active":
            if set(raw_record) != ACTIVE_SKILL_KEYS:
                raise ManifestError(f"active skill '{name}' has invalid key shape")
            directory = _normalize_posix_path(
                raw_record.get("directory"), f"active skill '{name}'.directory"
            )
            if directory != f"skills/{name}":
                raise ManifestError(f"active skill '{name}' directory must be skills/{name}")
            active_names.add(name)
        else:
            raise ManifestError(f"skill '{name}': state must be planned or active")
        records[name] = raw_record

    dependencies = manifest.get("skill_dependencies")
    if dependencies != PINNED_SKILL_DEPENDENCIES:
        raise ManifestError("skill_dependencies must match the pinned two-row/seven-edge graph")

    skills_root = root / "skills"
    if skills_root.exists() or _is_link_or_junction(skills_root):
        if not skills_root.is_dir():
            raise ManifestError("skills path must be a directory")
        _require_contained(skills_root, root, "skills root")
        actual_directories: set[str] = set()
        actual_root_files: list[str] = []
        for candidate in _walk_no_links(skills_root):
            relative = candidate.relative_to(skills_root)
            if len(relative.parts) == 1:
                if candidate.is_dir():
                    actual_directories.add(candidate.name)
                elif candidate.is_file():
                    actual_root_files.append(candidate.name)
        if actual_root_files:
            raise ManifestError(
                f"unexpected file(s) at skills root: {', '.join(sorted(actual_root_files))}"
            )
        planned_directories = sorted(actual_directories - active_names)
        if planned_directories:
            known_planned = [name for name in planned_directories if name in expected_names]
            unexpected = [name for name in planned_directories if name not in expected_names]
            if known_planned:
                raise ManifestError(
                    f"planned skill directory exists: {', '.join(known_planned)}"
                )
            raise ManifestError(f"unexpected skill directory: {', '.join(unexpected)}")
    elif active_names:
        raise ManifestError("active skill tree is missing")

    for name in expected_names:
        record = records[name]
        if record["state"] == "active":
            _validate_active_skill(
                root, record, active_names, expected_names, dependencies
            )
    return active_names, records


def _validate_required_identities(
    body: str, name: str, required_skills: list[str], catalog: tuple[str, ...]
) -> None:
    inside, outside = _block(body, REQUIRED_START, REQUIRED_END, f"agent '{name}' required-skill identities")
    pairs: list[tuple[str, str]] = []
    for line in inside.splitlines():
        if not line.strip():
            continue
        match = REQUIRED_LINE.fullmatch(line)
        if match is None:
            raise ManifestError(f"agent '{name}': malformed required-skill identities line: {line}")
        pairs.append((match.group("copilot"), match.group("claude")))
    expected = [(skill, skill) for skill in required_skills]
    if pairs != expected:
        raise ManifestError(f"agent '{name}': required-skill identities do not match canonical list")
    declared = set(required_skills)
    for line_number, context in _instruction_contexts(outside):
        for target in _action_targets(context, catalog):
            if target not in declared:
                raise ManifestError(
                    f"agent '{name}' body:{line_number}: undeclared mandatory load '{target}'"
                )


def _validate_agents(
    manifest: dict, root: Path, catalog: tuple[str, ...]
) -> list[dict]:
    agents = manifest.get("agents")
    if not isinstance(agents, list):
        raise ManifestError("agents: expected a list")
    names: list[str] = []
    expected_bodies: set[str] = set()
    for index, agent in enumerate(agents):
        where = f"agent[{index}]"
        if not isinstance(agent, dict) or set(agent) != AGENT_KEYS:
            raise ManifestError(f"{where}: exact canonical agent key set is required")
        name = _require_string(agent["name"], f"{where}.name")
        if not NAME_RE.fullmatch(name):
            raise ManifestError(f"{where}.name: expected kebab-case")
        if name in names:
            raise ManifestError(f"agents: duplicate name: {name}")
        names.append(name)
        description = _require_string(agent["description"], f"agent '{name}'.description")
        if len(description.encode("utf-8")) > 600:
            raise ManifestError(f"agent '{name}'.description exceeds 600 UTF-8 bytes")
        if "Triggers:" not in description:
            raise ManifestError(f"agent '{name}'.description lacks Triggers")
        body = _normalize_posix_path(agent["body"], f"agent '{name}'.body", prefix="agents")
        if body != f"agents/{name}.md":
            raise ManifestError(f"agent '{name}'.body must be agents/{name}.md")
        expected_bodies.add(body)
        capabilities = _require_string_list(
            agent["capabilities"], f"agent '{name}'.capabilities"
        )
        if not capabilities or not set(capabilities) <= KNOWN_CAPABILITIES:
            raise ManifestError(f"agent '{name}': unknown or empty capability list")
        required = _require_string_list(
            agent["required_skills"], f"agent '{name}'.required_skills"
        )
        unknown_required = sorted(set(required) - set(catalog))
        if unknown_required:
            raise ManifestError(
                f"agent '{name}' has unknown required skill(s): {', '.join(unknown_required)}"
            )
        if name in PINNED_AGENT_REQUIRED_SKILLS and required != PINNED_AGENT_REQUIRED_SKILLS[name]:
            raise ManifestError(f"agent '{name}' required-skill row drifted from the pinned matrix")
        _require_string_list(agent["delegates_to"], f"agent '{name}'.delegates_to")
        if not isinstance(agent["handoffs"], list):
            raise ManifestError(f"agent '{name}'.handoffs: expected a list")
        for handoff_index, handoff in enumerate(agent["handoffs"]):
            if not isinstance(handoff, dict) or set(handoff) != HANDOFF_KEYS:
                raise ManifestError(
                    f"agent '{name}' handoff[{handoff_index}]: exact key set is required"
                )
            _require_string(handoff["agent"], f"agent '{name}' handoff.agent")
            _require_string(handoff["label"], f"agent '{name}' handoff.label")
            _require_string(handoff["prompt"], f"agent '{name}' handoff.prompt")
            if handoff["send"] is not False:
                raise ManifestError(f"agent '{name}' handoff.send must be false")

    known = set(names)
    for agent in agents:
        name = agent["name"]
        for target in agent["delegates_to"]:
            if target not in known:
                raise ManifestError(f"agent '{name}' delegates to unknown agent '{target}'")
            if target == name:
                raise ManifestError(f"agent '{name}' cannot delegate to itself")
        for handoff in agent["handoffs"]:
            target = handoff["agent"]
            if target not in known:
                raise ManifestError(f"agent '{name}' hands off to unknown agent '{target}'")

    agent_root = root / "canonical" / "agents"
    actual_bodies: set[str] = set()
    if agent_root.exists() or _is_link_or_junction(agent_root):
        _require_contained(agent_root, root / "canonical", "canonical agent root")
        for candidate in _walk_no_links(agent_root):
            if candidate.is_file():
                actual_bodies.add(
                    f"agents/{candidate.relative_to(agent_root).as_posix()}"
                )
    if actual_bodies != expected_bodies:
        missing = sorted(expected_bodies - actual_bodies)
        extra = sorted(actual_bodies - expected_bodies)
        raise ManifestError(
            f"canonical agent body inventory drifted; missing={missing}, unexpected={extra}"
        )

    for agent in agents:
        body_path = root / "canonical" / PurePosixPath(agent["body"])
        _require_contained(body_path, root / "canonical", f"agent '{agent['name']}' body")
        if _is_hardlinked_file(body_path):
            raise ManifestError(f"agent '{agent['name']}' body cannot be a hardlink")
        raw = body_path.read_bytes()
        if not raw.endswith(b"\n"):
            raise ManifestError(f"agent '{agent['name']}' body must end with LF")
        try:
            body = raw.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise ManifestError(f"agent '{agent['name']}' body must be UTF-8") from exc
        _validate_required_identities(
            body, agent["name"], agent["required_skills"], catalog
        )
    return agents


def _validate_commands(manifest: dict, root: Path, state: str) -> list[dict]:
    commands = manifest.get("commands")
    if not isinstance(commands, list):
        raise ManifestError("commands: expected a list")
    if state == "boundary-only" and commands != []:
        raise ManifestError("format boundary not accepted: production commands must remain empty")

    command_root = root / "canonical" / "commands"
    actual_sources: set[str] = set()
    if command_root.exists() or _is_link_or_junction(command_root):
        _require_contained(command_root, root / "canonical", "canonical command root")
        for candidate in _walk_no_links(command_root):
            if candidate.is_file():
                source = f"commands/{candidate.relative_to(command_root).as_posix()}"
                actual_sources.add(source)
                if state != "boundary-only":
                    continue
                raise ManifestError(
                    "format boundary not accepted: unexpected canonical command body "
                    f"{candidate.relative_to(root).as_posix()}"
                )

    names: list[str] = []
    expected_sources: set[str] = set()
    for index, command in enumerate(commands):
        where = f"command[{index}]"
        if not isinstance(command, dict):
            raise ManifestError(f"{where}: expected an object")
        _unknown_keys(command, COMMAND_KEYS, where)
        missing_keys = sorted(COMMAND_KEYS - set(command))
        if missing_keys:
            raise ManifestError(f"{where}: missing key(s): {', '.join(missing_keys)}")
        name = _require_string(command["name"], f"{where}.name")
        if not NAME_RE.fullmatch(name):
            raise ManifestError(f"{where}.name: expected kebab-case")
        if name in names:
            raise ManifestError(f"commands: duplicate name: {name}")
        names.append(name)

        source = _normalize_posix_path(
            command["source"], f"command '{name}'.source", prefix="commands"
        )
        expected_source = f"commands/{name}.md"
        if source != expected_source:
            raise ManifestError(f"command '{name}'.source must be {expected_source}")
        expected_sources.add(source)

        description = _require_string(
            command["description"], f"command '{name}'.description"
        )
        if len(description.encode("utf-8")) > 600:
            raise ManifestError(f"command '{name}'.description exceeds 600 UTF-8 bytes")
        if "Triggers:" not in description:
            raise ManifestError(f"command '{name}'.description lacks Triggers")

        argument_mode = command["argument_mode"]
        if argument_mode not in {"required", "none"}:
            raise ManifestError(
                f"command '{name}'.argument_mode must be required or none"
            )
        argument_usage = command["argument_usage"]
        if argument_mode == "required":
            _require_string(argument_usage, f"command '{name}'.argument_usage")
        elif argument_usage != "":
            raise ManifestError(
                f"command '{name}'.argument_usage must be empty when argument_mode is none"
            )
        if command["invocation_mode"] != "manual":
            raise ManifestError(f"command '{name}'.invocation_mode must be manual")

    if actual_sources != expected_sources:
        missing = sorted(expected_sources - actual_sources)
        extra = sorted(actual_sources - expected_sources)
        raise ManifestError(
            f"canonical command body inventory drifted; missing={missing}, unexpected={extra}"
        )

    for command in commands:
        name = command["name"]
        body_path = root / "canonical" / PurePosixPath(command["source"])
        _require_contained(body_path, root / "canonical", f"command '{name}' body")
        if _is_hardlinked_file(body_path):
            raise ManifestError(f"command '{name}' body cannot be a hardlink")
        raw = body_path.read_bytes()
        if not raw or not raw.endswith(b"\n"):
            raise ManifestError(f"command '{name}' body must be nonempty and end with LF")
        if b"\r" in raw:
            raise ManifestError(f"command '{name}' body must use LF-only line endings")
        try:
            body = raw.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise ManifestError(f"command '{name}' body must be UTF-8") from exc
        expected_sentinels = 1 if command["argument_mode"] == "required" else 0
        if body.count(ARGUMENT_SENTINEL) != expected_sentinels:
            raise ManifestError(
                f"command '{name}' argument sentinel count must be {expected_sentinels}"
            )
        interpolation = RUNTIME_INTERPOLATION.search(body)
        if interpolation is not None:
            raise ManifestError(
                f"command '{name}' body contains runtime argument expression "
                f"{interpolation.group(0)}"
            )
        catalog = tuple(skill_name for skill_name, _task in PINNED_SKILLS)
        for line_number, context in _instruction_contexts(body):
            targets = _action_targets(context, catalog)
            if targets:
                raise ManifestError(
                    f"command '{name}' body:{line_number}: mandatory load '{targets[0]}' "
                    "is not allowed"
                )
    return commands


def _ready_agents(agents: list[dict], active_skills: set[str]) -> list[str]:
    ready = {
        agent["name"]
        for agent in agents
        if set(agent["required_skills"]) <= active_skills
    }
    by_name = {agent["name"]: agent for agent in agents}
    changed = True
    while changed:
        changed = False
        for name in tuple(ready):
            agent = by_name[name]
            targets = set(agent["delegates_to"]) | {
                handoff["agent"] for handoff in agent["handoffs"]
            }
            if not targets <= ready:
                ready.remove(name)
                changed = True
    return [agent["name"] for agent in agents if agent["name"] in ready]


def validate_manifest(
    manifest: dict, root: Path, *, require_content_complete: bool = False
) -> list[str]:
    root = _require_root(root)
    if not isinstance(manifest, dict):
        raise ManifestError("canonical manifest must be an object")
    _unknown_keys(manifest, TOP_KEYS, "top-level")
    if set(manifest) != TOP_KEYS:
        missing = sorted(TOP_KEYS - set(manifest))
        raise ManifestError(f"top-level: missing key(s): {', '.join(missing)}")
    if manifest["schema_version"] != 1:
        raise ManifestError("schema_version must be 1")
    _validate_plugin(manifest)
    _validate_models(manifest)
    state = manifest["assembly_state"]
    if state not in ASSEMBLY_STATES:
        raise ManifestError(f"assembly_state must be one of {sorted(ASSEMBLY_STATES)}")
    if require_content_complete and state != "content-complete":
        raise ManifestError("--require-content-complete requires assembly_state content-complete")

    canonical = root / "canonical"
    _require_contained(canonical, root, "canonical root")
    _validate_default_discovery(root)
    _validate_commands(manifest, root, state)
    active_skills, _records = _validate_skills(manifest, root)
    catalog = tuple(name for name, _task in PINNED_SKILLS)
    agents = _validate_agents(manifest, root, catalog)
    ready = _ready_agents(agents, active_skills)

    if state == "boundary-only" and active_skills:
        raise ManifestError("boundary-only assembly cannot contain active skills")
    if state == "content-complete":
        if len(active_skills) != len(PINNED_SKILLS):
            raise ManifestError("content-complete requires all 26 skills active")
        agent_names = tuple(agent["name"] for agent in agents)
        if agent_names != CONTENT_COMPLETE_AGENTS:
            raise ManifestError("content-complete requires the exact five-agent roster")
        if ready != list(CONTENT_COMPLETE_AGENTS):
            raise ManifestError("content-complete requires all five agents runtime-ready")
    return ready


def load_manifest(root: Path) -> dict:
    root = _require_root(root)
    canonical = root / "canonical"
    _require_contained(canonical, root, "canonical root")
    path = canonical / "fleet.json"
    _require_contained(path, canonical, "canonical manifest")
    if _is_hardlinked_file(path):
        raise ManifestError(f"canonical manifest cannot be a hardlink: {path}")
    try:
        with path.open(encoding="utf-8", newline="") as handle:
            value = json.load(handle, object_pairs_hook=_reject_duplicate_json_keys)
    except ManifestError:
        raise
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ManifestError(f"cannot read canonical manifest: {exc}") from exc
    return value


def load_and_validate(
    root: Path, *, require_content_complete: bool = False
) -> tuple[dict, list[str]]:
    manifest = load_manifest(root)
    ready = validate_manifest(
        manifest, root, require_content_complete=require_content_complete
    )
    return manifest, ready


def _json_bytes(value: object) -> bytes:
    return (json.dumps(value, indent=2, ensure_ascii=False) + "\n").encode("utf-8")


def _flow_list(values: list[str]) -> str:
    return "[" + ", ".join("'" + value.replace("'", "''") + "'" for value in values) + "]"


def _body(root: Path, agent: dict) -> tuple[str, str]:
    raw = (root / "canonical" / PurePosixPath(agent["body"])).read_bytes()
    return raw.decode("utf-8"), hashlib.sha256(raw).hexdigest()


def _command_body(root: Path, command: dict) -> tuple[str, str]:
    raw = (root / "canonical" / PurePosixPath(command["source"])).read_bytes()
    return raw.decode("utf-8"), hashlib.sha256(raw).hexdigest()


def _command_view(root: Path, command: dict, runtime: str) -> bytes:
    body, body_hash = _command_body(root, command)
    expression = COMMAND_ARGUMENT_EXPRESSIONS[runtime]
    if command["argument_mode"] == "required":
        body = body.replace(ARGUMENT_SENTINEL, expression)
    lines = [
        "---",
        f"{GENERATED_BANNER} from canonical/fleet.json and canonical/{command['source']}; "
        f"body-sha256={body_hash}; DO NOT EDIT.",
    ]
    if runtime == "fallback":
        lines.append(f"name: {command['name']}")
    lines.append(
        f"description: {json.dumps(command['description'], ensure_ascii=False)}"
    )
    if command["argument_mode"] == "required":
        lines.append(
            f"argument-hint: {json.dumps(command['argument_usage'], ensure_ascii=False)}"
        )
    if runtime in {"copilot", "claude"}:
        lines.append("disable-model-invocation: true")
    lines.extend(["---", body])
    return "\n".join(lines).encode("utf-8")


def _copilot_agent(root: Path, agent: dict, models: dict) -> bytes:
    tools = [capability for capability in agent["capabilities"]]
    if agent["delegates_to"]:
        tools.append("agent")
    body, body_hash = _body(root, agent)
    lines = [
        "---",
        f"{GENERATED_BANNER} from canonical/fleet.json and canonical/{agent['body']}; "
        f"body-sha256={body_hash}; DO NOT EDIT.",
        f"name: {agent['name']}",
        f"description: {json.dumps(agent['description'], ensure_ascii=False)}",
        f"tools: {_flow_list(tools)}",
    ]
    if models["copilot"]:
        lines.append(f"model: {_flow_list(models['copilot'])}")
    if agent["delegates_to"]:
        lines.append(f"agents: {_flow_list(agent['delegates_to'])}")
    if agent["handoffs"]:
        lines.append("handoffs:")
        for handoff in agent["handoffs"]:
            lines.extend(
                [
                    f"  - agent: {handoff['agent']}",
                    f"    label: {json.dumps(handoff['label'], ensure_ascii=False)}",
                    f"    prompt: {json.dumps(handoff['prompt'], ensure_ascii=False)}",
                    "    send: false",
                ]
            )
    lines.extend(["---", body])
    return "\n".join(lines).encode("utf-8")


def _claude_agent(root: Path, agent: dict, models: dict) -> bytes:
    capabilities = set(agent["capabilities"])
    tools: list[str] = []
    if "read" in capabilities:
        tools.append("Read")
    if "search" in capabilities:
        tools.extend(("Grep", "Glob"))
    if "execute" in capabilities and agent["name"] not in {"sre", "observer"}:
        tools.append("Bash")
    if "edit" in capabilities:
        tools.extend(("Edit", "Write"))
    if "web" in capabilities:
        tools.extend(("WebSearch", "WebFetch"))
    if agent["required_skills"]:
        tools.append("Skill")
    if agent["delegates_to"]:
        tools.append(f"Agent({', '.join(agent['delegates_to'])})")
    body, body_hash = _body(root, agent)
    lines = [
        "---",
        f"{GENERATED_BANNER} from canonical/fleet.json and canonical/{agent['body']}; "
        f"body-sha256={body_hash}; DO NOT EDIT.",
        f"name: {agent['name']}",
        f"description: {json.dumps(agent['description'], ensure_ascii=False)}",
        f"tools: {', '.join(tools)}",
    ]
    if models["claude"] is not None:
        lines.append(f"model: {json.dumps(models['claude'], ensure_ascii=False)}")
    lines.extend(["---", body])
    return "\n".join(lines).encode("utf-8")


def _plugin_manifest(manifest: dict, ready: list[str], runtime: str) -> dict:
    plugin = manifest["plugin"]
    active = [skill for skill in manifest["skills"] if skill["state"] == "active"]
    if runtime == "copilot":
        result = dict(plugin)
        result["agents"] = "./generated/copilot/agents/" if ready else []
    else:
        result = {key: value for key, value in plugin.items() if key != "displayName"}
        result["agents"] = [
            f"./generated/claude/agents/{name}.md" for name in ready
        ]
    commands = manifest["commands"]
    result["skills"] = "./skills/" if active else []
    if runtime == "copilot":
        result["commands"] = "./generated/copilot/commands/" if commands else []
    else:
        result["commands"] = [
            f"./generated/claude/commands/{command['name']}.md"
            for command in commands
        ]
    return result


def render(root: Path, manifest: dict, ready: list[str] | None = None) -> dict[Path, bytes]:
    root = _require_root(root)
    validated_ready = validate_manifest(manifest, root)
    if ready is not None and ready != validated_ready:
        raise ManifestError("caller-supplied ready set does not match canonical readiness")
    ready = validated_ready
    models = _validate_models(manifest)
    by_name = {agent["name"]: agent for agent in manifest["agents"]}
    outputs: dict[Path, bytes] = {
        Path("plugin.json"): _json_bytes(_plugin_manifest(manifest, ready, "copilot")),
        Path(".claude-plugin/plugin.json"): _json_bytes(
            _plugin_manifest(manifest, ready, "claude")
        ),
        Path("hooks.json"): _json_bytes({"hooks": {}}),
        Path("hooks/hooks.json"): _json_bytes({"hooks": {}}),
    }
    for name in ready:
        agent = by_name[name]
        outputs[Path(f"generated/copilot/agents/{name}.agent.md")] = _copilot_agent(
            root, agent, models
        )
        outputs[Path(f"generated/claude/agents/{name}.md")] = _claude_agent(
            root, agent, models
        )
    for command in manifest["commands"]:
        name = command["name"]
        outputs[Path(f"generated/copilot/commands/{name}.md")] = _command_view(
            root, command, "copilot"
        )
        outputs[Path(f"generated/copilot/prompts/{name}.prompt.md")] = _command_view(
            root, command, "fallback"
        )
        outputs[Path(f"generated/claude/commands/{name}.md")] = _command_view(
            root, command, "claude"
        )
    return outputs


def _safe_parent(root: Path, parent: Path) -> None:
    root = _require_root(root)
    try:
        relative = parent.absolute().relative_to(root)
    except ValueError as exc:
        raise ManifestError(f"output parent escapes fleet root: {parent}") from exc
    current = root
    for part in relative.parts:
        current = current / part
        if _is_link_or_junction(current):
            raise ManifestError(f"output parent is a link or junction: {current}")
        if current.exists() and not current.is_dir():
            raise ManifestError(f"output parent component is not a directory: {current}")
        if not current.exists():
            current.mkdir()


def _preflight_outputs(root: Path) -> None:
    for relative in ROOT_OUTPUTS:
        target = root / relative
        _require_contained(target, root, "generated output", exists=False)
        if target.exists() and _is_hardlinked_file(target):
            raise ManifestError(f"generated output is a hardlink: {target}")
    for relative in OWNED_DIRECTORIES:
        tree = root / relative
        if not tree.exists() and not _is_link_or_junction(tree):
            continue
        for candidate in _walk_no_links(tree):
            if candidate.is_file() and _is_hardlinked_file(candidate):
                raise ManifestError(f"generated output is a hardlink: {candidate}")


def _actual_owned_files(root: Path) -> set[Path]:
    actual: set[Path] = set()
    for relative in OWNED_DIRECTORIES:
        tree = root / relative
        if not tree.exists() and not _is_link_or_junction(tree):
            continue
        for candidate in _walk_no_links(tree):
            if candidate.is_file():
                actual.add(candidate.relative_to(root))
    return actual


def check(root: Path, *, require_content_complete: bool = False) -> list[str]:
    root = _require_root(root)
    manifest, ready = load_and_validate(
        root, require_content_complete=require_content_complete
    )
    expected = render(root, manifest, ready)
    _preflight_outputs(root)
    failures: list[str] = []
    for relative, content in sorted(expected.items(), key=lambda item: item[0].as_posix()):
        target = root / relative
        if not target.is_file():
            failures.append(f"missing generated output: {relative.as_posix()}")
        elif target.read_bytes() != content:
            failures.append(f"stale generated output: {relative.as_posix()}")
    expected_owned = {
        relative
        for relative in expected
        if any(relative == owned or owned in relative.parents for owned in OWNED_DIRECTORIES)
    }
    for relative in sorted(_actual_owned_files(root) - expected_owned, key=lambda path: path.as_posix()):
        failures.append(f"unexpected generated output: {relative.as_posix()}")
    return failures


def _atomic_write(root: Path, target: Path, content: bytes) -> None:
    _safe_parent(root, target.parent)
    if _is_link_or_junction(target):
        raise ManifestError(f"generated output is a link or junction: {target}")
    if target.exists() and _is_hardlinked_file(target):
        raise ManifestError(f"generated output is a hardlink: {target}")
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{target.name}.", suffix=".tmp", dir=target.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, target)
    except Exception:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass
        raise


def write(root: Path, *, require_content_complete: bool = False) -> None:
    root = _require_root(root)
    manifest, ready = load_and_validate(
        root, require_content_complete=require_content_complete
    )
    expected = render(root, manifest, ready)
    _preflight_outputs(root)
    expected_owned = {
        relative
        for relative in expected
        if any(relative == owned or owned in relative.parents for owned in OWNED_DIRECTORIES)
    }
    stale = _actual_owned_files(root) - expected_owned
    for relative in sorted(stale, key=lambda path: (len(path.parts), path.as_posix()), reverse=True):
        target = root / relative
        if _is_link_or_junction(target) or _is_hardlinked_file(target):
            raise ManifestError(f"unsafe stale generated output: {target}")
        target.unlink()
    for relative in sorted(OWNED_DIRECTORIES, key=lambda path: len(path.parts), reverse=True):
        tree = root / relative
        if not tree.exists():
            continue
        for current, _directories, _files in os.walk(tree, topdown=False):
            current_path = Path(current)
            if current_path != tree:
                try:
                    current_path.rmdir()
                except OSError:
                    pass
    for relative, content in sorted(expected.items(), key=lambda item: item[0].as_posix()):
        _atomic_write(root, root / relative, content)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate owned outputs")
    mode.add_argument("--check", action="store_true", help="fail when owned outputs drift")
    parser.add_argument(
        "--require-content-complete",
        action="store_true",
        help="also require the final 26-skill/five-agent closed state",
    )
    args = parser.parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    try:
        if args.write:
            write(root, require_content_complete=args.require_content_complete)
            print("generate_fleet: WRITE PASS")
            return 0
        failures = check(root, require_content_complete=args.require_content_complete)
    except ManifestError as exc:
        print(f"generate_fleet: FAIL: {exc}", file=sys.stderr)
        return 1
    if failures:
        print("generate_fleet: FAIL", file=sys.stderr)
        for failure in failures:
            print(f"  {failure}", file=sys.stderr)
        return 1
    print("generate_fleet: CHECK PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
